#[cfg(feature = "gpu")]
pub mod active_substrate;
pub mod area_manager;
pub mod attractors;
pub mod cf;
pub mod coherence;
pub mod competition;
pub mod diagnostics;
pub mod entropy;
pub mod hilbert;
pub mod kernel;
pub mod memory;
pub mod observation;
pub mod physics;
pub mod pxl1;
#[cfg(feature = "gpu")]
pub mod render;
pub mod rng;
pub mod semantics;
pub mod sit;
pub mod spatial;
pub mod telemetry;
pub mod world;
