"""
endpoint API Endpoint
Generated by Neural Shell
"""

from flask import Blueprint, request, jsonify

endpoint_bp = Blueprint('endpoint', __name__)

@endpoint_bp.route('/endpoint', methods=['GET', 'POST'])
def endpoint_endpoint():
    """
    endpoint endpoint
    """
    if request.method == 'GET':
        # Handle GET request
        return jsonify({
            'status': 'success',
            'endpoint': 'endpoint',
            'message': 'endpoint endpoint working'
        })

    elif request.method == 'POST':
        # Handle POST request
        data = request.get_json()
        return jsonify({
            'status': 'success',
            'received_data': data,
            'message': 'Data processed successfully'
        })

    return jsonify({'error': 'Method not allowed'}), 405
