"""
Python to GeoASM Transpiler

Transpiles Python source code to GeoASM assembly language.

Supports:
- Annotated assignment (ast.AnnAssign): x: int = 5
- Async for loops (ast.AsyncFor): async for x in iter:
- Async with statements (ast.AsyncWith): async with ctx:
- Type annotation extraction: emits TYPE: comments
- Delete statements: del arr[start:stop]
"""

import ast
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set
from enum import Enum


class OpCode(Enum):
    """GeoASM operation codes"""
    NOP = 0x00
    HALT = 0x02
    JMP = 0x04
    JEQ = 0x05
    JNE = 0x06
    JLT = 0x07
    JGT = 0x0B
    JLE = 0x0C
    JGE = 0x0D
    CALL = 0x08
    RET = 0x09
    PUSH = 0x10
    POP = 0x11
    LDR = 0x40
    STR = 0x41
    LDR_IMM = 0x42
    STR_IMM = 0x43
    MOVI = 0x49
    ADD = 0x80
    SUB = 0x82
    MUL = 0x84
    DIV = 0x86
    AND = 0xA0
    OR = 0xA1
    XOR = 0xA2
    NOT = 0xA3
    # Glyph primitives
    SET_COLOR = 0xC0
    DRAW_CHAR = 0xC1
    DRAW_LINE = 0xC2
    DRAW_RECT = 0xC3
    FILL_RECT = 0xC4
    GLYPH_DEFINE = 0xC5
    GLYPH_BLIT = 0xC6
    ORB = 0xCA
    PANEL = 0xCB
    HEATMAP_CELL = 0xCE
    DRAW_PIXEL = 0xCF
    # Async/FFI
    ASYNC_AWAIT = 0xD0
    ASYNC_START = 0xD1
    ASYNC_END = 0xD2
    # Memory operations
    DEL = 0xE0
    DEL_RANGE = 0xE1


@dataclass
class RegisterAllocator:
    """Manages register allocation during transpilation"""
    next_reg: int = 0
    used_regs: Set[int] = field(default_factory=set)
    var_to_reg: Dict[str, int] = field(default_factory=dict)

    def allocate(self, var_name: str = None) -> int:
        """Allocate a new register"""
        if var_name and var_name in self.var_to_reg:
            return self.var_to_reg[var_name]

        reg = self.next_reg
        self.next_reg += 1
        self.used_regs.add(reg)
        if var_name:
            self.var_to_reg[var_name] = reg
        return reg

    def get(self, var_name: str) -> int:
        """Get register for variable, allocating if needed"""
        if var_name not in self.var_to_reg:
            return self.allocate(var_name)
        return self.var_to_reg[var_name]

    def free(self, var_name: str):
        """Free a register"""
        if var_name in self.var_to_reg:
            reg = self.var_to_reg[var_name]
            self.used_regs.discard(reg)
            del self.var_to_reg[var_name]


@dataclass
class TranspileContext:
    """Context for transpilation"""
    allocator: RegisterAllocator = field(default_factory=RegisterAllocator)
    output: List[str] = field(default_factory=list)
    label_counter: int = 0
    type_annotations: Dict[str, str] = field(default_factory=dict)
    debug_mode: bool = False
    async_state: Optional[str] = None  # Current async state machine state

    def emit(self, instruction: str, comment: str = None):
        """Emit an instruction"""
        if comment:
            self.output.append(f"    {instruction}  ; {comment}")
        else:
            self.output.append(f"    {instruction}")

    def emit_comment(self, comment: str):
        """Emit a comment"""
        self.output.append(f"    ; {comment}")

    def emit_type(self, var_name: str, type_str: str):
        """Emit type annotation comment"""
        self.type_annotations[var_name] = type_str
        self.emit_comment(f"TYPE: {var_name} : {type_str}")

    def new_label(self, prefix: str = "L") -> str:
        """Generate a new unique label"""
        self.label_counter += 1
        return f"{prefix}_{self.label_counter}"

    def get_output(self) -> str:
        """Get the full output"""
        return "\n".join(self.output)


class PythonToGeoASM:
    """
    Transpiles Python source code to GeoASM assembly.

    Usage:
        t = PythonToGeoASM()
        result = t.transpile('x: int = 5')
        print(result)  # MOVI R0, 5  ; TYPE: x : int
    """

    def __init__(self, debug_mode: bool = False):
        self.debug_mode = debug_mode
        self.type_metadata: Dict[str, str] = {}  # Stores type annotations

    def transpile(self, source: str) -> str:
        """
        Transpile Python source code to GeoASM assembly.

        Args:
            source: Python source code string

        Returns:
            GeoASM assembly code string
        """
        # Clear type metadata for new transpilation
        self.type_metadata = {}

        # Parse the source
        try:
            tree = ast.parse(source)
        except SyntaxError as e:
            return f"; ERROR: Syntax error: {e}"

        # Create context
        ctx = TranspileContext(debug_mode=self.debug_mode)

        # Emit header
        ctx.emit_comment("Generated by PythonToGeoASM transpiler")
        ctx.emit("")

        # Transpile all statements
        for stmt in tree.body:
            self._transpile_stmt(stmt, ctx)

        # Copy type annotations to instance
        self.type_metadata = ctx.type_annotations.copy()

        # Emit HALT at end
        ctx.emit("HALT")

        return ctx.get_output()

    def _transpile_stmt(self, stmt: ast.stmt, ctx: TranspileContext):
        """Transpile a single statement"""
        method_name = f"_transpile_{stmt.__class__.__name__}"
        method = getattr(self, method_name, None)
        if method:
            method(stmt, ctx)
        else:
            ctx.emit_comment(f"TODO: {stmt.__class__.__name__}")

    def _transpile_AnnAssign(self, stmt: ast.AnnAssign, ctx: TranspileContext):
        """Handle annotated assignment: x: int = 5"""
        # Extract variable name
        if isinstance(stmt.target, ast.Name):
            var_name = stmt.target.id
        else:
            var_name = str(stmt.annotation)

        # Extract type annotation
        type_str = self._extract_type_string(stmt.annotation)
        ctx.emit_type(var_name, type_str)

        # If there's a value, transpile it
        if stmt.value:
            reg = ctx.allocator.get(var_name)
            self._transpile_expr_to_reg(stmt.value, reg, ctx)

            # Store to memory (variable address is based on allocation order)
            addr = ctx.allocator.get(var_name)  # Use register number as address
            ctx.emit(f"STR_IMM R{reg}, {addr}", f"store {var_name}")

            # Emit debug type check in debug mode
            if ctx.debug_mode:
                ctx.emit(f"ASSERT_TYPE R{reg}, {type_str}", "runtime type check")
        else:
            # Declaration only - emit comment
            ctx.emit_comment(f"type annotation only: {var_name} : {type_str}")

    def _transpile_Assign(self, stmt: ast.Assign, ctx: TranspileContext):
        """Handle regular assignment: x = 5"""
        for target in stmt.targets:
            if isinstance(target, ast.Name):
                var_name = target.id
                reg = ctx.allocator.get(var_name)
                self._transpile_expr_to_reg(stmt.value, reg, ctx)
            elif isinstance(target, ast.Subscript):
                # Array subscript assignment: arr[i] = value
                self._transpile_subscript_assign(target, stmt.value, ctx)

    def _transpile_Delete(self, stmt: ast.Delete, ctx: TranspileContext):
        """Handle delete statement: del x or del arr[i] or del arr[start:stop]"""
        for target in stmt.targets:
            if isinstance(target, ast.Name):
                # Simple variable delete
                var_name = target.id
                ctx.emit(f"del {var_name}", f"variable deleted")
                ctx.allocator.free(var_name)

            elif isinstance(target, ast.Subscript):
                # Subscript delete: del arr[i] or del arr[start:stop]
                self._transpile_delete_subscript(target, ctx)

            elif isinstance(target, ast.Attribute):
                # Attribute delete: del obj.attr
                attr_name = target.attr
                obj_name = self._get_expr_name(target.value)
                ctx.emit(f"del .{attr_name}", f"attribute cleared")

    def _transpile_delete_subscript(self, target: ast.Subscript, ctx: TranspileContext):
        """Handle subscript delete: del arr[i] or del arr[start:stop]"""
        # Get array name
        arr_name = self._get_expr_name(target.value)
        arr_reg = ctx.allocator.get(arr_name)

        if isinstance(target.slice, ast.Slice):
            # Slice delete: del arr[start:stop] or del arr[start:stop:step]
            start_reg = ctx.allocator.allocate()
            stop_reg = ctx.allocator.allocate()

            if target.slice.lower:
                self._transpile_expr_to_reg(target.slice.lower, start_reg, ctx)
            else:
                ctx.emit(f"MOVI R{start_reg}, 0", "slice start at 0")

            if target.slice.upper:
                self._transpile_expr_to_reg(target.slice.upper, stop_reg, ctx)
            else:
                ctx.emit(f"MOVI R{stop_reg}, 0xFFFF", "open-ended slice")

            # Handle step
            if target.slice.step:
                step_reg = ctx.allocator.allocate()
                self._transpile_expr_to_reg(target.slice.step, step_reg, ctx)
                ctx.emit(f"SLICE_DEL_STEP R{arr_reg}, R{start_reg}, R{stop_reg}, R{step_reg}", f"slice removed with step")
                ctx.allocator.used_regs.discard(step_reg)
            else:
                # Emit MEMMOVE optimization hint for bulk operations
                ctx.emit_comment("MEMMOVE optimization: bulk shift elements")
                ctx.emit(f"SLICE_DEL_LOOP R{arr_reg}, R{start_reg}, R{stop_reg}", f"slice removed from {arr_name}")

            # Update length
            ctx.emit(f"SUB R{arr_reg}, R{stop_reg}, R{start_reg}", "update array length")
            ctx.emit(f"STR R{arr_reg}, [len_{arr_name}]", "store new length")

            # Free temp registers
            ctx.allocator.used_regs.discard(start_reg)
            ctx.allocator.used_regs.discard(stop_reg)

        elif isinstance(target.slice, ast.Tuple):
            # Extended slice: del arr[i, j]
            ctx.emit_comment(f"Extended slice delete on {arr_name}")
            for i, idx in enumerate(target.slice.elts):
                idx_reg = ctx.allocator.allocate()
                self._transpile_expr_to_reg(idx, idx_reg, ctx)
                ctx.emit(f"DEL_IDX R{arr_reg}, R{idx_reg}", f"delete element {i}")
                ctx.allocator.used_regs.discard(idx_reg)

        elif isinstance(target.slice, ast.UnaryOp) and isinstance(target.slice.op, ast.USub):
            # Negative index: del arr[-1]
            idx_reg = ctx.allocator.allocate()
            self._transpile_expr_to_reg(target.slice, idx_reg, ctx)
            ctx.emit(f"NEG_IDX R{arr_reg}, R{idx_reg}", f"del arr at negative index")
            ctx.allocator.used_regs.discard(idx_reg)

        elif isinstance(target.value, ast.Subscript):
            # Nested subscript: del arr[i][j]
            # First get the outer subscript
            outer_reg = ctx.allocator.allocate()
            self._transpile_expr_to_reg(target.value, outer_reg, ctx)
            idx_reg = ctx.allocator.allocate()
            self._transpile_expr_to_reg(target.slice, idx_reg, ctx)
            ctx.emit(f"NESTED_DEL R{outer_reg}, R{idx_reg}", f"nested subscript delete")
            ctx.allocator.used_regs.discard(outer_reg)
            ctx.allocator.used_regs.discard(idx_reg)

        else:
            # Single index delete: del arr[i]
            idx_reg = ctx.allocator.allocate()
            self._transpile_expr_to_reg(target.slice, idx_reg, ctx)
            ctx.emit(f"DEL_SHIFT_LOOP R{arr_reg}, R{idx_reg}", f"element removed from {arr_name}")
            ctx.emit(f"SUB R{arr_reg}, R{arr_reg}, 1", "update array length")
            ctx.emit(f"STR R{arr_reg}, [len_{arr_name}]", "store new length")
            ctx.allocator.used_regs.discard(idx_reg)

    def _transpile_subscript_assign(self, target: ast.Subscript, value: ast.expr, ctx: TranspileContext):
        """Handle subscript assignment: arr[i] = value"""
        arr_name = self._get_expr_name(target.value)
        arr_reg = ctx.allocator.get(arr_name)

        # Get index
        idx_reg = ctx.allocator.allocate()
        self._transpile_expr_to_reg(target.slice, idx_reg, ctx)

        # Get value
        val_reg = ctx.allocator.allocate()
        self._transpile_expr_to_reg(value, val_reg, ctx)

        # Store to array element
        ctx.emit(f"STR_ARRAY R{arr_reg}, R{idx_reg}, R{val_reg}", f"assign to {arr_name}[i]")

        # Free temp registers
        ctx.allocator.used_regs.discard(idx_reg)
        ctx.allocator.used_regs.discard(val_reg)

    def _transpile_AsyncFor(self, stmt: ast.AsyncFor, ctx: TranspileContext):
        """Handle async for loop: async for x in iter:"""
        # Create labels for the loop
        loop_start = ctx.new_label("ASYNC_FOR_START")
        loop_end = ctx.new_label("ASYNC_FOR_END")

        # Get iterator
        iter_reg = ctx.allocator.allocate()
        self._transpile_expr_to_reg(stmt.iter, iter_reg, ctx)

        # Emit ASYNC_FOR start marker
        ctx.emit(f"ASYNC_FOR_START R{iter_reg}", "begin async for loop")

        # Loop start label
        ctx.emit(f"{loop_start}:")

        # Check if more items (simplified - actual impl would check iterator)
        ctx.emit(f"JEQ R{iter_reg}, 0, {loop_end}", "check iterator exhausted")

        # Get next item with AWAIT marker
        item_reg = ctx.allocator.get(stmt.target.id)
        ctx.emit(f"AWAIT", "await next item")
        ctx.emit(f"ASYNC_NEXT R{iter_reg}, R{item_reg}", "get next item")

        # Transpile loop body
        for body_stmt in stmt.body:
            self._transpile_stmt(body_stmt, ctx)

        # Jump back to loop start
        ctx.emit(f"JMP {loop_start}")

        # Loop end label
        ctx.emit(f"{loop_end}:")
        ctx.emit("ASYNC_ENDFOR", "end async for loop")

    def _transpile_AsyncWith(self, stmt: ast.AsyncWith, ctx: TranspileContext):
        """Handle async with statement: async with ctx:"""
        # Create state machine labels
        enter_label = ctx.new_label("ASYNC_WITH_ENTER")
        exit_label = ctx.new_label("ASYNC_WITH_EXIT")

        # Get context expression from first withitem
        if stmt.items:
            item = stmt.items[0]
            ctx_reg = ctx.allocator.allocate()
            self._transpile_expr_to_reg(item.context_expr, ctx_reg, ctx)
        else:
            ctx_reg = ctx.allocator.allocate()

        # Emit async enter with AWAIT marker
        ctx.emit(f"{enter_label}:")
        ctx.emit(f"AWAIT", "await __aenter__")
        ctx.emit(f"ASYNC_AENTER R{ctx_reg}", "enter async context")

        # Store context in optional variable
        if stmt.items and stmt.items[0].optional_vars:
            target = stmt.items[0].optional_vars
            if isinstance(target, ast.Name):
                var_reg = ctx.allocator.get(target.id)
                ctx.emit(f"MOVI R{var_reg}, [async_context+0]", f"store {target.id}")

        # Transpile body
        for body_stmt in stmt.body:
            self._transpile_stmt(body_stmt, ctx)

        # Emit async exit with AWAIT marker
        ctx.emit(f"{exit_label}:")
        ctx.emit(f"AWAIT", "await __aexit__")
        ctx.emit(f"ASYNC_AEXIT R{ctx_reg}", "exit async context")

    def _transpile_Expr(self, stmt: ast.Expr, ctx: TranspileContext):
        """Handle expression statement (function call, etc.)"""
        if isinstance(stmt.value, ast.Call):
            self._transpile_call(stmt.value, ctx)
        else:
            ctx.emit_comment(f"TODO: Expr statement {type(stmt.value).__name__}")

    def _transpile_For(self, stmt: ast.For, ctx: TranspileContext):
        """Handle for loop: for x in iter:"""
        loop_start = ctx.new_label("FOR_START")
        loop_end = ctx.new_label("FOR_END")

        # Get iterator
        iter_reg = ctx.allocator.allocate()
        self._transpile_expr_to_reg(stmt.iter, iter_reg, ctx)

        # Loop start
        ctx.emit(f"{loop_start}:")
        ctx.emit(f"JEQ R{iter_reg}, 0, {loop_end}", "check iterator")

        # Get next item
        item_reg = ctx.allocator.get(stmt.target.id)
        ctx.emit(f"NEXT R{iter_reg}, R{item_reg}", "get next item")

        # Transpile body
        for body_stmt in stmt.body:
            self._transpile_stmt(body_stmt, ctx)

        ctx.emit(f"JMP {loop_start}")
        ctx.emit(f"{loop_end}:")

    def _transpile_While(self, stmt: ast.While, ctx: TranspileContext):
        """Handle while loop"""
        loop_start = ctx.new_label("WHILE_START")
        loop_end = ctx.new_label("WHILE_END")

        ctx.emit(f"{loop_start}:")

        # Check condition
        cond_reg = ctx.allocator.allocate()
        self._transpile_expr_to_reg(stmt.test, cond_reg, ctx)
        ctx.emit(f"JEQ R{cond_reg}, 0, {loop_end}", "check while condition")

        # Transpile body
        for body_stmt in stmt.body:
            self._transpile_stmt(body_stmt, ctx)

        ctx.emit(f"JMP {loop_start}")
        ctx.emit(f"{loop_end}:")

    def _transpile_If(self, stmt: ast.If, ctx: TranspileContext):
        """Handle if statement"""
        else_label = ctx.new_label("IF_ELSE")
        end_label = ctx.new_label("IF_END")

        # Check condition
        cond_reg = ctx.allocator.allocate()
        self._transpile_expr_to_reg(stmt.test, cond_reg, ctx)
        ctx.emit(f"JEQ R{cond_reg}, 0, {else_label}", "check if condition")

        # Transpile body
        for body_stmt in stmt.body:
            self._transpile_stmt(body_stmt, ctx)
        ctx.emit(f"JMP {end_label}")

        # Else branch
        ctx.emit(f"{else_label}:")
        if stmt.orelse:
            for else_stmt in stmt.orelse:
                self._transpile_stmt(else_stmt, ctx)

        ctx.emit(f"{end_label}:")

    def _transpile_Return(self, stmt: ast.Return, ctx: TranspileContext):
        """Handle return statement"""
        if stmt.value:
            ret_reg = ctx.allocator.allocate()
            self._transpile_expr_to_reg(stmt.value, ret_reg, ctx)
            ctx.emit(f"RET R{ret_reg}")
        else:
            ctx.emit("RET")

    def _transpile_Pass(self, stmt: ast.Pass, ctx: TranspileContext):
        """Handle pass statement"""
        ctx.emit("NOP", "pass")

    def _transpile_AsyncFunctionDef(self, stmt: ast.AsyncFunctionDef, ctx: TranspileContext):
        """Handle async function definition - transpile the body"""
        ctx.emit_comment(f"async def {stmt.name}()")
        # Transpile the function body
        for body_stmt in stmt.body:
            self._transpile_stmt(body_stmt, ctx)

    def _transpile_FunctionDef(self, stmt: ast.FunctionDef, ctx: TranspileContext):
        """Handle function definition - transpile the body"""
        ctx.emit_comment(f"def {stmt.name}()")
        # Transpile the function body
        for body_stmt in stmt.body:
            self._transpile_stmt(body_stmt, ctx)

    def _transpile_call(self, call: ast.Call, ctx: TranspileContext):
        """Handle function call"""
        func_name = self._get_expr_name(call.func)

        # Handle built-in functions
        if func_name == "print":
            # Print arguments
            for arg in call.args:
                arg_reg = ctx.allocator.allocate()
                self._transpile_expr_to_reg(arg, arg_reg, ctx)
                ctx.emit(f"PRINT R{arg_reg}")
            return

        # Generic function call
        ctx.emit(f"CALL {func_name}")

    def _transpile_expr_to_reg(self, expr: ast.expr, reg: int, ctx: TranspileContext):
        """Transpile expression and store result in register"""
        if isinstance(expr, ast.Constant):
            # Immediate value
            ctx.emit(f"MOVI R{reg}, {expr.value}")

        elif isinstance(expr, ast.Name):
            # Variable reference
            src_reg = ctx.allocator.get(expr.id)
            if src_reg != reg:
                ctx.emit(f"MOV R{reg}, R{src_reg}")

        elif isinstance(expr, ast.BinOp):
            # Binary operation
            left_reg = ctx.allocator.allocate()
            right_reg = ctx.allocator.allocate()

            self._transpile_expr_to_reg(expr.left, left_reg, ctx)
            self._transpile_expr_to_reg(expr.right, right_reg, ctx)

            op_map = {
                ast.Add: "ADD",
                ast.Sub: "SUB",
                ast.Mult: "MUL",
                ast.Div: "DIV",
                ast.BitOr: "OR",
                ast.BitAnd: "AND",
                ast.BitXor: "XOR",
            }

            op_name = op_map.get(type(expr.op), "ADD")
            ctx.emit(f"{op_name} R{reg}, R{left_reg}, R{right_reg}")

            ctx.allocator.used_regs.discard(left_reg)
            ctx.allocator.used_regs.discard(right_reg)

        elif isinstance(expr, ast.Compare):
            # Comparison
            left_reg = ctx.allocator.allocate()
            self._transpile_expr_to_reg(expr.left, left_reg, ctx)

            # For simplicity, emit comparison result (0 or 1)
            ctx.emit(f"CMP R{reg}, R{left_reg}", "compare")
            ctx.allocator.used_regs.discard(left_reg)

        elif isinstance(expr, ast.Subscript):
            # Array subscript
            arr_name = self._get_expr_name(expr.value)
            arr_reg = ctx.allocator.get(arr_name)
            idx_reg = ctx.allocator.allocate()
            self._transpile_expr_to_reg(expr.slice, idx_reg, ctx)
            ctx.emit(f"LDR_ARRAY R{reg}, R{arr_reg}, R{idx_reg}")
            ctx.allocator.used_regs.discard(idx_reg)

        elif isinstance(expr, ast.Call):
            # Function call result
            self._transpile_call(expr, ctx)
            ctx.emit(f"MOV R{reg}, R0", "store call result")

        else:
            ctx.emit_comment(f"TODO: expression type {type(expr).__name__}")

    def _get_expr_name(self, expr: ast.expr) -> str:
        """Get name from expression"""
        if isinstance(expr, ast.Name):
            return expr.id
        elif isinstance(expr, ast.Attribute):
            return f"{self._get_expr_name(expr.value)}.{expr.attr}"
        return "expr"

    def _extract_type_string(self, annotation: ast.expr) -> str:
        """Extract type annotation as string"""
        if isinstance(annotation, ast.Name):
            return annotation.id
        elif isinstance(annotation, ast.Subscript):
            value = self._extract_type_string(annotation.value)
            slice_str = self._extract_type_string(annotation.slice)
            return f"{value}[{slice_str}]"
        elif isinstance(annotation, ast.Tuple):
            elements = [self._extract_type_string(e) for e in annotation.elts]
            return ", ".join(elements)
        elif isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
            left = self._extract_type_string(annotation.left)
            right = self._extract_type_string(annotation.right)
            return f"{left} | {right}"
        elif isinstance(annotation, ast.Constant):
            return str(annotation.value)
        elif isinstance(annotation, ast.Attribute):
            return self._get_expr_name(annotation)
        return str(annotation)


# Convenience function
def transpile(source: str, debug_mode: bool = False) -> str:
    """
    Transpile Python source code to GeoASM.

    Args:
        source: Python source code string
        debug_mode: Enable debug mode (emits type checks)

    Returns:
        GeoASM assembly code string
    """
    transpiler = PythonToGeoASM(debug_mode=debug_mode)
    return transpiler.transpile(source)


if __name__ == "__main__":
    # Demo
    examples = [
        "x: int = 5",
        "y: list[int] = [1, 2, 3]",
        "async for x in items:\n    print(x)",
        "del arr[5:10]",
    ]

    for example in examples:
        print(f"Python: {example}")
        print(f"GeoASM:\n{transpile(example)}")
        print()
