"""
Test Vector Simulation
Verifies the integration of the Simulator into the Computational Substrate.
Demonstrates the 'Think -> Simulate -> Build' loop.
"""

import os
import sys
import numpy as np
import time

# Add src to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from runtime.computational_substrate import ComputationalSubstrate
from runtime.vector_state_machine import VectorStateMachine
# Mock KnowledgeDistiller for this test as it's not the focus
class MockDistiller:
    def __init__(self):
        self.conn = None
        self.knowledge_index = {}
    
    def _create_embedding(self, text):
        # Deterministic dummy embedding
        seed = sum(ord(c) for c in text)
        rng = np.random.RandomState(seed)
        vec = rng.uniform(-1, 1, 128)
        return vec / np.linalg.norm(vec)

def test_simulation_loop():
    print("🧪 Starting Vector Simulation Test...")
    
    # 1. Setup Environment
    # Use in-memory DB for VSM to avoid clutter
    vsm = VectorStateMachine(":memory:")
    distiller = MockDistiller()
    substrate = ComputationalSubstrate(distiller, vsm)
    
    # 2. Define Problem (Think Phase)
    # We want to transform 'Current State' to 'Goal State'
    input_concept = "Process A (Inefficient)"
    goal_concept = "Process A (Optimized)"
    
    print(f"\n🧠 THINK PHASE:")
    print(f"   Inputs: {input_concept}")
    print(f"   Goal: {goal_concept}")
    
    # 3. Simulate Phase
    # We propose a transformation logic (the 'Idea')
    # Let's say we define a python function that mathematically rotates the vector towards the goal
    # (In reality, this logic would be code generated by the LLM)
    
    simulation_logic = """
def transform(vec):
    # Simulate an optimization step: shift vector slightly
    # In a real scenario this might be architectural logic
    return vec * 1.1 + 0.05
"""
    
    print(f"\n💭 SIMULATE PHASE:")
    print("   Simulating computational idea: 'Linear Optimization Strategy'")
    
    result = substrate.simulate(
        idea_name="Linear Optimization Strategy",
        input_concept=input_concept,
        logic=simulation_logic,
        goal_concept=goal_concept
    )
    
    # 4. Analyze Results
    print(f"\n📊 ANALYSIS PHASE:")
    print(f"   Simulation ID: {result['simulation_id']}")
    print(f"   Success: {result['success']}")
    print(f"   Outcome Score: {result['outcome_score']:.4f}")
    if result['outcome_score'] > 0.5:
        print("   ✅ Conclusion: Idea is viable for Build phase.")
    else:
        print("   ❌ Conclusion: Idea requires refinement.")
        
    print("\n✅ Test Complete")

if __name__ == "__main__":
    test_simulation_loop()
