// Integration test: C transpiler end-to-end
//
// Pipeline: C source -> Python transpiler -> .gasm text -> Rust assembler -> software_vm
// The .gasm text below was generated by tools/c_transpiler/transpiler.py from C source.
// We verify the assembled program runs correctly on the software VM.

use pixels_move_pixels::assembler::parse_gasm;
use pixels_move_pixels::software_vm::SoftwareVm;

/// Helper: load .gasm program into VM, set initial registers, run, return VM state.
fn run_gasm_with_args(gasm: &str, args: &[(usize, u32)]) -> pixels_move_pixels::vm::VmState {
    let program = parse_gasm(gasm).expect(".gasm should parse successfully");
    let mut svm = SoftwareVm::new();
    svm.load_program(0, &program.pixels);
    svm.spawn_vm(0, 0);
    // Set initial register values before executing
    {
        let vm = &mut svm.vms[0];
        for &(reg, val) in args {
            vm.regs[reg] = val;
        }
    }
    svm.execute_frame();
    svm.vm_state(0).clone()
}

const FACTORIAL_GASM: &str = "\
; Function: factorial
func_factorial:
;   param: n -> r0
;   int result -> r8
LDI r31, 1
MOV r8, r31
while_1:
LDI r30, 1
BGE r30, r0, endwhile_2
MUL r8, r0
LDI r30, 1
SUB r0, r30
JMP while_1
endwhile_2:
MOV r0, r8
HALT
; End function: factorial
NOP";

const MAX_GASM: &str = "\
; Function: max
func_max:
;   param: a -> r0
;   param: b -> r1
BGE r1, r0, else_1
HALT
JMP endif_2
else_1:
MOV r0, r1
HALT
endif_2:
; End function: max
NOP";

const SUM_TO_GASM: &str = "\
; Function: sum_to
func_sum_to:
;   param: n -> r0
;   int sum -> r8
;   int i -> r9
LDI r31, 0
MOV r8, r31
LDI r30, 0
MOV r9, r30
for_1:
BGE r9, r0, endfor_2
ADD r8, r9
step_3:
LDI r29, 1
ADD r9, r29
JMP for_1
endfor_2:
MOV r0, r8
HALT
; End function: sum_to
NOP";

#[test]
fn transpile_factorial_5() {
    let vm = run_gasm_with_args(FACTORIAL_GASM, &[(0, 5)]);
    assert_eq!(vm.regs[0], 120, "factorial(5) should return 120");
    assert_eq!(vm.halted, 1, "VM should have halted");
}

#[test]
fn transpile_factorial_1() {
    let vm = run_gasm_with_args(FACTORIAL_GASM, &[(0, 1)]);
    assert_eq!(vm.regs[0], 1, "factorial(1) should return 1");
}

#[test]
fn transpile_factorial_0() {
    let vm = run_gasm_with_args(FACTORIAL_GASM, &[(0, 0)]);
    assert_eq!(vm.regs[0], 1, "factorial(0) should return 1");
}

#[test]
fn transpile_max_10_25() {
    let vm = run_gasm_with_args(MAX_GASM, &[(0, 10), (1, 25)]);
    assert_eq!(vm.regs[0], 25, "max(10, 25) should return 25");
    assert_eq!(vm.halted, 1, "VM should have halted");
}

#[test]
fn transpile_max_25_10() {
    let vm = run_gasm_with_args(MAX_GASM, &[(0, 25), (1, 10)]);
    assert_eq!(vm.regs[0], 25, "max(25, 10) should return 25");
    assert_eq!(vm.halted, 1, "VM should have halted");
}

#[test]
fn transpile_max_equal() {
    let vm = run_gasm_with_args(MAX_GASM, &[(0, 42), (1, 42)]);
    assert_eq!(vm.regs[0], 42, "max(42, 42) should return 42");
}

#[test]
fn transpile_sum_to_6() {
    let vm = run_gasm_with_args(SUM_TO_GASM, &[(0, 6)]);
    assert_eq!(vm.regs[0], 15, "sum_to(6) should return 15 (0+1+2+3+4+5)");
    assert_eq!(vm.halted, 1, "VM should have halted");
}

#[test]
fn transpile_sum_to_0() {
    let vm = run_gasm_with_args(SUM_TO_GASM, &[(0, 0)]);
    assert_eq!(vm.regs[0], 0, "sum_to(0) should return 0");
}

// ── GEO-44: Struct, Pointer, Array e2e tests ─────────────────────────
//
// Frame pointer r6 must be set to a safe memory region (well past program code).
// We use 0x1000 (4096) which gives pixel index 1024 for the first variable.

const STRUCT_PTR_GASM: &str = "\
;   struct Point (8 bytes, 2 fields)
; Generated by c_transpiler.py
;
; Function: test_struct_ptr
func_test_struct_ptr:
;   struct Point p at frame+0 (8B)
;   int* px -> r8
LDI r31, 0
ADD r31, r6
MOV r8, r31
LDI r31, 42
;   ; convert byte addr r8 to pixel index
LDI r29, 2
MOV r30, r8
SHR r30, r29
STORE r30, r31
;   ; convert byte addr r8 to pixel index
MOV r30, r8
LDI r29, 2
SHR r30, r29
LOAD r31, r30
MOV r0, r31
HALT
; End function: test_struct_ptr
NOP";

const BYTEARR_GASM: &str = "\
; Generated by c_transpiler.py
;
; Function: test_bytearr
func_test_bytearr:
;   char[8] buf at frame+0 (8B)
LDI r31, 0
ADD r31, r6
LDI r30, 0
ADD r31, r30
LDI r30, 65
STB r31, r30
LDI r30, 0
ADD r30, r6
LDI r29, 1
ADD r30, r29
LDI r29, 66
STB r30, r29
LDI r29, 0
ADD r29, r6
LDI r28, 0
ADD r29, r28
LDB r28, r29
MOV r0, r28
HALT
; End function: test_bytearr
NOP";

const SUM_ARRAY_GASM: &str = "\
; Generated by c_transpiler.py
;
; Function: sum_array
func_sum_array:
;   int[4] arr at frame+0 (16B)
;   int* p -> r8
;   int sum -> r9
;   int i -> r10
LDI r31, 0
ADD r31, r6
LDI r30, 0
LDI r29, 4
MUL r30, r29
ADD r31, r30
LDI r30, 10
;   ; convert byte addr r31 to pixel index
LDI r28, 2
MOV r29, r31
SHR r29, r28
STORE r29, r30
LDI r30, 0
ADD r30, r6
LDI r29, 1
LDI r28, 4
MUL r29, r28
ADD r30, r29
LDI r29, 20
;   ; convert byte addr r30 to pixel index
LDI r27, 2
MOV r28, r30
SHR r28, r27
STORE r28, r29
LDI r29, 0
ADD r29, r6
LDI r28, 2
LDI r27, 4
MUL r28, r27
ADD r29, r28
LDI r28, 30
;   ; convert byte addr r29 to pixel index
LDI r26, 2
MOV r27, r29
SHR r27, r26
STORE r27, r28
LDI r28, 0
ADD r28, r6
LDI r27, 3
LDI r26, 4
MUL r27, r26
ADD r28, r27
LDI r27, 40
;   ; convert byte addr r28 to pixel index
LDI r25, 2
MOV r26, r28
SHR r26, r25
STORE r26, r27
LDI r27, 0
MOV r9, r27
LDI r27, 0
ADD r27, r6
LDI r26, 0
LDI r25, 4
MUL r26, r25
ADD r27, r26
MOV r8, r27
LDI r27, 0
MOV r10, r27
for_1:
LDI r27, 4
BGE r10, r27, endfor_2
;   ; convert byte addr r8 to pixel index
MOV r26, r8
LDI r25, 2
SHR r26, r25
LOAD r27, r26
MOV r26, r9
ADD r26, r27
MOV r9, r26
LDI r26, 1
MOV r25, r8
LDI r24, 4
MUL r26, r24
ADD r25, r26
MOV r8, r25
step_3:
LDI r25, 1
MOV r24, r10
ADD r24, r25
MOV r10, r24
JMP for_1
endfor_2:
MOV r0, r9
HALT
; End function: sum_array
NOP";

const DOT_ACCESS_GASM: &str = "\
;   struct Entry (8 bytes, 2 fields)
; Generated by c_transpiler.py
;
; Function: test_dot_access
func_test_dot_access:
;   struct Entry e at frame+0 (8B)
LDI r31, 0
ADD r31, r6
LDI r30, 5
;   ; convert byte addr r31 to pixel index
LDI r28, 2
MOV r29, r31
SHR r29, r28
STORE r29, r30
LDI r30, 0
ADD r30, r6
LDI r29, 4
ADD r30, r29
LDI r29, 0
ADD r29, r6
;   ; convert byte addr r29 to pixel index
MOV r27, r29
LDI r26, 2
SHR r27, r26
LOAD r28, r27
LDI r27, 10
ADD r28, r27
;   ; convert byte addr r30 to pixel index
LDI r26, 2
MOV r27, r30
SHR r27, r26
STORE r27, r28
LDI r28, 0
ADD r28, r6
LDI r27, 4
ADD r28, r27
;   ; convert byte addr r28 to pixel index
MOV r26, r28
LDI r25, 2
SHR r26, r25
LOAD r27, r26
MOV r0, r27
HALT
; End function: test_dot_access
NOP";

/// Frame pointer base address for struct/array tests.
/// Must be well past the program code. 0x1000 = 4096 bytes.
const FRAME_PTR: u32 = 0x1000;

/// GEO-44: Struct write/read via pointer.
/// C: struct Point { int x; int y; }; px = &p.x; *px = 42; return *px;
/// Expected: r0 = 42
#[test]
fn transpile_struct_ptr() {
    let vm = run_gasm_with_args(STRUCT_PTR_GASM, &[(6, FRAME_PTR)]);
    assert_eq!(vm.regs[0], 42, "struct pointer write/read should return 42");
    assert_eq!(vm.halted, 1, "VM should have halted");
}

/// GEO-44: Byte array (char array) with LDB/STB.
/// C: char buf[8]; buf[0] = 65; buf[1] = 66; return buf[0];
/// Expected: r0 = 65
#[test]
fn transpile_byte_array() {
    let vm = run_gasm_with_args(BYTEARR_GASM, &[(6, FRAME_PTR)]);
    assert_eq!(vm.regs[0], 65, "byte array read should return 65 (ASCII 'A')");
    assert_eq!(vm.halted, 1, "VM should have halted");
}

/// GEO-44: Array iteration with pointer arithmetic.
/// C: int arr[4]={10,20,30,40}; sum=0; p=&arr[0]; for(i=0;i<4;i++) { sum+=*p; p++; } return sum;
/// Expected: r0 = 100
#[test]
fn transpile_sum_array() {
    let vm = run_gasm_with_args(SUM_ARRAY_GASM, &[(6, FRAME_PTR)]);
    assert_eq!(vm.regs[0], 100, "sum_array should return 100 (10+20+30+40)");
    assert_eq!(vm.halted, 1, "VM should have halted");
}

/// GEO-44: Struct field access via dot notation.
/// C: struct Entry { int key; int value; }; e.key=5; e.value=e.key+10; return e.value;
/// Expected: r0 = 15
#[test]
fn transpile_struct_dot_access() {
    let vm = run_gasm_with_args(DOT_ACCESS_GASM, &[(6, FRAME_PTR)]);
    assert_eq!(vm.regs[0], 15, "struct dot access should return 15 (5+10)");
    assert_eq!(vm.halted, 1, "VM should have halted");
}
