// Auto-generated by pixel-llm bridge
// 18 pixels at address 500

use pixels_move_pixels::vm::GlyphVm;

#[test]
fn llm_generated_program() {
    let mut vm = GlyphVm::new();

    // Load LLM-generated program
    let pixels: Vec<u32> = vec![0x00000001, 0x00000000, 0x00010001, 0x00000064, 0x00020001, 0x00000000, 0x00030001, 0x00000001, 0x00040001, 0x0000001C, 0x00050003, 0x05010004, 0x03000005, 0x03010005, 0x03020005, 0x0402010A, 0x000000F9, 0x0000000D];
    vm.substrate().load_program(500, &pixels);
    vm.spawn_vm(0, 500);
    vm.execute_frame();

    // Program ran successfully if we get here without panic
    println!("LLM program executed: {} pixels, {} instructions",
        18,
        18 / 2,  // rough estimate
    );
}
