// GEO-47 E2E test: Minix FS read via C transpiler
//
// This is the big proof: real C code (minix_read.c) transpiled to .glyph,
// running on the software VM, successfully reading a file from a Minix v2
// disk image loaded into VM memory.
//
// Pipeline:
//   1. Load transpiled .glyph program at address 0
//   2. Load minix_test.img bytes into VM memory at DISK_BASE
//   3. Set r0=DISK_BASE, r1=RESULT_BASE
//   4. Run VM
//   5. Verify r0=5 and result buffer contains "HELLO"

use pixels_move_pixels::assembler::parse_gasm;
use pixels_move_pixels::software_vm::SoftwareVm;

/// Byte address where disk image is loaded (pixel 256)
const DISK_BASE: u32 = 1024;
/// Byte address for result buffer (pixel 1536)
const RESULT_BASE: u32 = 6144;

/// Load raw bytes into VM memory starting at byte_addr.
/// Converts bytes to little-endian u32 words and loads via Hilbert mapping.
fn load_bytes_into_vm(svm: &mut SoftwareVm, byte_addr: u32, data: &[u8]) {
    let pixel_start = byte_addr / 4;
    // Pad to word alignment
    let padded_len = (data.len() + 3) & !3;
    let mut padded = data.to_vec();
    padded.resize(padded_len, 0);
    let mut pixels = Vec::with_capacity(padded_len / 4);
    for chunk in padded.chunks(4) {
        let word = u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
        pixels.push(word);
    }
    svm.load_program(pixel_start, &pixels);
}

/// Load the .glyph program transpiled from minix_read.c.
///
/// Generated by: python3 tools/c_transpiler/transpiler.py examples/minix_read.c
///
/// The program reads:
///   - Superblock magic at disk+526 (bytes 0x68, 0x24)
///   - Inode at disk+2048: i_size at +4, zone[0] at +28
///   - File data at disk + zone[0]*512
///   - Copies file_size bytes to result buffer using LDB/STB
const MINIX_READ_GASM: &str = "\
; Generated by c_transpiler.py
; 
; Function: minix_read
func_minix_read:
;   param: disk -> r0
;   param: result -> r1
;   int sb_off -> r8
;   int inode_off -> r9
;   int data_off -> r10
;   int file_size -> r11
;   int zone_num -> r12
;   int i -> r13
;   int b -> r14
LDI r31, 526
MOV r30, r0
ADD r30, r31
MOV r8, r30
LDB r30, r8
MOV r14, r30
LDI r30, 104
BEQ r14, r30, endif_2
LDI r30, 0
MOV r0, r30
HALT
endif_2:
LDI r29, 1
MOV r28, r8
ADD r28, r29
LDB r27, r28
MOV r14, r27
LDI r27, 36
BEQ r14, r27, endif_4
LDI r27, 0
MOV r0, r27
HALT
endif_4:
LDI r26, 2048
MOV r25, r0
ADD r25, r26
MOV r9, r25
LDI r25, 4
MOV r24, r9
ADD r24, r25
;   ; convert byte addr r24 to pixel index
MOV r22, r24
LDI r21, 2
SHR r22, r21
LOAD r23, r22
MOV r11, r23
LDI r23, 28
MOV r22, r9
ADD r22, r23
;   ; convert byte addr r22 to pixel index
MOV r20, r22
LDI r19, 2
SHR r20, r19
LOAD r21, r20
MOV r12, r21
LDI r21, 512
MOV r20, r12
MUL r20, r21
MOV r19, r0
ADD r19, r20
MOV r10, r19
LDI r19, 0
MOV r13, r19
while_5:
BGE r13, r11, endwhile_6
MOV r19, r10
ADD r19, r13
LDB r18, r19
MOV r14, r18
MOV r18, r1
ADD r18, r13
STB r18, r14
LDI r18, 1
MOV r17, r13
ADD r17, r18
MOV r13, r17
JMP while_5
endwhile_6:
MOV r0, r11
HALT
; End function: minix_read
NOP";

/// Read up to `len` bytes from VM memory starting at byte_addr.
fn read_bytes_from_vm(svm: &SoftwareVm, byte_addr: u32, len: usize) -> Vec<u8> {
    let mut result = Vec::with_capacity(len);
    // Read byte-by-byte using the same logic as LDB
    for i in 0..len {
        let addr = byte_addr + i as u32;
        let pixel_idx = addr / 4;
        let pixel = svm.read_pixel(pixel_idx);
        let byte_offset = (addr % 4) as usize;
        let byte_val = ((pixel >> (byte_offset * 8)) & 0xFF) as u8;
        result.push(byte_val);
    }
    result
}

/// Helper: run .gasm program with initial register values
fn run_gasm(gasm: &str, args: &[(usize, u32)]) -> pixels_move_pixels::vm::VmState {
    let program = parse_gasm(gasm).expect(".gasm should parse");
    let mut svm = SoftwareVm::new();
    svm.load_program(0, &program.pixels);
    svm.spawn_vm(0, 0);
    {
        let vm = &mut svm.vms[0];
        for &(reg, val) in args {
            vm.regs[reg] = val;
        }
    }
    svm.execute_frame();
    svm.vm_state(0).clone()
}

#[test]
fn minix_read_hello() {
    let program = parse_gasm(MINIX_READ_GASM).expect(".gasm should parse");
    let mut svm = SoftwareVm::new();
    
    // Load program at address 0
    svm.load_program(0, &program.pixels);
    svm.spawn_vm(0, 0);
    
    // Load disk image into VM memory
    let disk_image = include_bytes!("fixtures/minix_test.img");
    load_bytes_into_vm(&mut svm, DISK_BASE, disk_image);
    
    // Set registers: r0=disk base, r1=result buffer base
    {
        let vm = &mut svm.vms[0];
        vm.regs[0] = DISK_BASE;   // disk image base address
        vm.regs[1] = RESULT_BASE; // result buffer address
    }
    
    // Execute
    svm.execute_frame();
    
    // Verify
    let state = svm.vm_state(0);
    assert_eq!(state.halted, 1, "VM should have halted");
    assert_eq!(state.regs[0], 5, "minix_read should return 5 (bytes read)");
    
    // Read result buffer
    let result = read_bytes_from_vm(&svm, RESULT_BASE, 5);
    assert_eq!(&result, b"HELLO", "Result buffer should contain 'HELLO'");
}

#[test]
fn minix_read_bad_magic() {
    // Use a zeroed disk image -- magic check should fail
    let program = parse_gasm(MINIX_READ_GASM).expect(".gasm should parse");
    let mut svm = SoftwareVm::new();
    
    svm.load_program(0, &program.pixels);
    svm.spawn_vm(0, 0);
    
    // Load zeros (no valid superblock)
    let zeros = vec![0u8; 4096];
    load_bytes_into_vm(&mut svm, DISK_BASE, &zeros);
    
    {
        let vm = &mut svm.vms[0];
        vm.regs[0] = DISK_BASE;
        vm.regs[1] = RESULT_BASE;
    }
    
    svm.execute_frame();
    
    let state = svm.vm_state(0);
    assert_eq!(state.halted, 1, "VM should have halted (error path)");
    assert_eq!(state.regs[0], 0, "minix_read should return 0 on bad magic");
}
