import os
import time
import json
from pathlib import Path
from publish_to_wp import publish_to_wordpress

# Geometry OS System Observer Blogger
# -----------------------------------
# Monitors the 'systems/' directory for new files or modifications
# and automatically publishes reports to the WordPress district.

class SystemObserverBlogger:
    def __init__(self, watch_dir="systems"):
        self.watch_dir = Path(watch_dir)
        self.last_state = self._get_directory_state()
        self.ignore_dirs = {'.git', '__pycache__', '.venv', 'node_modules'}

    def _get_directory_state(self):
        """Map of relative paths to modification times."""
        state = {}
        for root, dirs, files in os.walk(self.watch_dir):
            # Skip ignored directories
            dirs[:] = [d for d in dirs if d not in self.ignore_dirs]
            
            for f in files:
                full_path = Path(root) / f
                rel_path = full_path.relative_to(self.watch_dir)
                try:
                    state[str(rel_path)] = os.path.getmtime(full_path)
                except OSError:
                    continue
        return state

    def check_for_changes(self):
        current_state = self._get_directory_state()
        new_files = []
        modified_files = []

        for path, mtime in current_state.items():
            if path not in self.last_state:
                new_files.append(path)
            elif mtime > self.last_state[path]:
                modified_files.append(path)

        if new_files or modified_files:
            self._publish_report(new_files, modified_files)
            self.last_state = current_state

    def _publish_report(self, new_files, modified_files):
        print(f"🧐 Detected changes in {self.watch_dir}")
        
        title = f"System Update: Architectural Evolution detected at {time.strftime('%H:%M:%S')}"
        
        content = "<h2>Structural Analysis Report</h2>"
        content += f"<p>The <b>Architect Prime</b> has detected evolution in the following system components:</p>"
        
        if new_files:
            content += "<h3>🆕 New Components</h3><ul>"
            for f in new_files:
                content += f"<li><code>{f}</code></li>"
            content += "</ul>"
            
        if modified_files:
            content += "<h3>⚡ Modified Modules</h3><ul>"
            for f in modified_files:
                content += f"<li><code>{f}</code></li>"
            content += "</ul>"
            
        content += f"<p><i>This report was automatically generated by the System Observer Agent.</i></p>"
        
        publish_to_wordpress(title, content)

    def run(self):
        print(f"🕵️ System Observer Blogger active. Watching '{self.watch_dir}'...")
        # First-run welcome post
        publish_to_wordpress(
            "Agent Integration Complete", 
            "<p>The System Observer Agent is now monitoring the Geometry OS architecture for evolutionary changes.</p>"
        )
        
        while True:
            try:
                self.check_for_changes()
                time.sleep(30) # Check every 30 seconds
            except KeyboardInterrupt:
                break
            except Exception as e:
                print(f"Error in observer: {e}")
                time.sleep(10)

if __name__ == "__main__":
    observer = SystemObserverBlogger()
    observer.run()
