"""Error codes and constants for Pixel LLM error handling."""

# Error code constants
ERR_CONNECTION_FAILED = "ERR_CONNECTION_FAILED"
ERR_CONNECTION_TIMEOUT = "ERR_CONNECTION_TIMEOUT"
ERR_CONNECTION_REFUSED = "ERR_CONNECTION_REFUSED"
ERR_SERVICE_UNAVAILABLE = "ERR_SERVICE_UNAVAILABLE"

ERR_TIMEOUT_LLM_INFERENCE = "ERR_TIMEOUT_LLM_INFERENCE"
ERR_TIMEOUT_API_REQUEST = "ERR_TIMEOUT_API_REQUEST"
ERR_TIMEOUT_ENCODER = "ERR_TIMEOUT_ENCODER"

ERR_VALIDATION_MISSING_FIELD = "ERR_VALIDATION_MISSING_FIELD"
ERR_VALIDATION_INVALID_FORMAT = "ERR_VALIDATION_INVALID_FORMAT"
ERR_VALIDATION_OUT_OF_RANGE = "ERR_VALIDATION_OUT_OF_RANGE"
ERR_VALIDATION_INVALID_TYPE = "ERR_VALIDATION_INVALID_TYPE"

ERR_API_HTTP_4XX = "ERR_API_HTTP_4XX"
ERR_API_HTTP_5XX = "ERR_API_HTTP_5XX"
ERR_API_RATE_LIMIT = "ERR_API_RATE_LIMIT"
ERR_API_INVALID_KEY = "ERR_API_INVALID_KEY"

ERR_ENCODER_VISION_FAILED = "ERR_ENCODER_VISION_FAILED"
ERR_ENCODER_EMBEDDING_FAILED = "ERR_ENCODER_EMBEDDING_FAILED"
ERR_ENCODER_PREPROCESSING_FAILED = "ERR_ENCODER_PREPROCESSING_FAILED"

ERR_CIRCUIT_BREAKER_OPEN = "ERR_CIRCUIT_BREAKER_OPEN"
ERR_CIRCUIT_BREAKER_TIMEOUT = "ERR_CIRCUIT_BREAKER_TIMEOUT"

ERR_RETRY_EXHAUSTED = "ERR_RETRY_EXHAUSTED"
ERR_CACHE_MISS = "ERR_CACHE_MISS"
ERR_UNKNOWN = "ERR_UNKNOWN"

# Categories
CONNECTION_ERROR_CODES = {ERR_CONNECTION_FAILED, ERR_CONNECTION_TIMEOUT, ERR_CONNECTION_REFUSED, ERR_SERVICE_UNAVAILABLE}
TIMEOUT_ERROR_CODES = {ERR_TIMEOUT_LLM_INFERENCE, ERR_TIMEOUT_API_REQUEST, ERR_TIMEOUT_ENCODER}
VALIDATION_ERROR_CODES = {ERR_VALIDATION_MISSING_FIELD, ERR_VALIDATION_INVALID_FORMAT, ERR_VALIDATION_OUT_OF_RANGE, ERR_VALIDATION_INVALID_TYPE}
API_ERROR_CODES = {ERR_API_HTTP_4XX, ERR_API_HTTP_5XX, ERR_API_RATE_LIMIT, ERR_API_INVALID_KEY}
ENCODER_ERROR_CODES = {ERR_ENCODER_VISION_FAILED, ERR_ENCODER_EMBEDDING_FAILED, ERR_ENCODER_PREPROCESSING_FAILED}
CIRCUIT_BREAKER_ERROR_CODES = {ERR_CIRCUIT_BREAKER_OPEN, ERR_CIRCUIT_BREAKER_TIMEOUT}
RETRY_ERROR_CODES = {ERR_CONNECTION_TIMEOUT, ERR_SERVICE_UNAVAILABLE, ERR_API_RATE_LIMIT, ERR_API_HTTP_5XX}

# Messages
ERROR_MESSAGES = {
    ERR_CONNECTION_FAILED: "Failed to connect to the remote service.",
    ERR_TIMEOUT_LLM_INFERENCE: "LLM inference took too long to complete.",
    ERR_UNKNOWN: "An unexpected error occurred.",
}

def get_error_message(code: str) -> str:
    return ERROR_MESSAGES.get(code, "An error occurred.")

def get_all_error_codes() -> list[str]:
    return list(ERROR_MESSAGES.keys())

def get_error_category(code: str) -> str:
    if code in CONNECTION_ERROR_CODES: return "CONNECTION"
    if code in TIMEOUT_ERROR_CODES: return "TIMEOUT"
    return "UNKNOWN"

def is_retryable_error(code: str) -> bool:
    return code in RETRY_ERROR_CODES

def is_client_error(code: str) -> bool:
    return code in VALIDATION_ERROR_CODES or code == ERR_API_HTTP_4XX
