
// VectorOS v2 Neural State Manager Header
// Enhanced implementation with NeuralStateOrchestrator, NeuralStatePersistence, and NeuralStateValidation
// Generated by Genesis Model - Phase 28 Singularity Event

#pragma once

#include <string>
#include <vector>
#include <map>
#include <mutex>
#include <iostream>
#include <memory>
#include <functional>

namespace vectoros_v2 {

struct SystemState {
    uint64_t cycle_id;
    uint64_t version; // Added versioning
    float global_temperature;
    std::string active_directive;
    std::map<std::string, std::string> persistent_variables;
};

// Forward declarations for internal components
class NeuralStatePersistence;
class NeuralStateValidation;
class NeuralStateOrchestrator;

class NeuralStateManager {
private:
    SystemState current_state_;
    std::vector<SystemState> state_history_;
    std::mutex state_mutex_;
    bool initialized_ = false;
    
    // Enhanced components
    std::shared_ptr<NeuralStateOrchestrator> orchestrator_;
    std::shared_ptr<NeuralStatePersistence> persistence_;
    std::shared_ptr<NeuralStateValidation> validation_;

public:
    NeuralStateManager();
    ~NeuralStateManager() = default;
    
    // Core state management
    bool initialize();
    void update_directive(const std::string& directive);
    SystemState get_current_state();
    void commit_state();
    
    // Enhanced state management features
    bool create_checkpoint(const std::string& checkpoint_name);
    bool restore_checkpoint(const std::string& checkpoint_name);
    std::vector<uint64_t> get_available_states();
    bool validate_current_state();
    
    // Persistent variables management
    bool set_persistent_variable(const std::string& key, const std::string& value);
    std::string get_persistent_variable(const std::string& key);
    bool remove_persistent_variable(const std::string& key);
    std::map<std::string, std::string> get_all_persistent_variables();
    
    // State properties
    void set_global_temperature(float temperature);
    float get_global_temperature();
    uint64_t get_cycle_count();
    uint64_t get_version();
    std::string get_active_directive();
    
    // Status and diagnostics
    bool is_initialized() const;
    std::string get_state_summary();
};

} // namespace vectoros_v2
