"""
Evolution Daemon V13 - Behavioral Monitor

Real-time behavioral monitoring for agent anomaly detection.

Tracks agent activity patterns and calculates anomaly scores based on
file operations, network operations, and entropy metrics.
"""

from datetime import datetime
from typing import Dict, Optional

from systems.evolution_daemon.safety.data_structures import (
    AgentBehavioralProfile,
    BehavioralEvent,
)


class BehavioralMonitor:
    """
    Monitors agent behavior for anomaly detection.

    The behavioral monitor tracks agent activities and calculates
    anomaly scores based on:
    - File operation frequency (40% weight)
    - Network operation frequency (30% weight)
    - Entropy of activity patterns (30% weight)

    Agents with anomaly scores above the threshold are flagged
    for potential tier elevation in the TierRouter.
    """

    # Anomaly detection thresholds
    ANOMALY_THRESHOLD = 0.7
    SLIDING_WINDOW_SECONDS = 300  # 5 minutes

    def __init__(
        self,
        anomaly_threshold: Optional[float] = None,
        sliding_window_seconds: Optional[int] = None
    ):
        """
        Initialize the behavioral monitor.

        Args:
            anomaly_threshold: Threshold for anomaly detection (default: 0.7)
            sliding_window_seconds: Time window for activity tracking (default: 300s)
        """
        self.anomaly_threshold = (
            anomaly_threshold if anomaly_threshold is not None
            else self.ANOMALY_THRESHOLD
        )
        self.sliding_window_seconds = (
            sliding_window_seconds if sliding_window_seconds is not None
            else self.SLIDING_WINDOW_SECONDS
        )

        # In-memory storage for agent profiles (MVP - no persistence)
        self._profiles: Dict[str, AgentBehavioralProfile] = {}

        # Event history for sliding window calculations
        self._event_history: Dict[str, list] = {}

    def record_event(
        self,
        agent_id: str,
        event_type: str,
        metadata: dict
    ) -> BehavioralEvent:
        """
        Record a behavioral event from an agent.

        Creates a BehavioralEvent, updates the agent's profile,
        and recalculates the anomaly score.

        Args:
            agent_id: Unique identifier for the agent
            event_type: Type of event (e.g., "file_read", "network_request")
            metadata: Additional event metadata

        Returns:
            The created BehavioralEvent
        """
        # Create the event
        event = BehavioralEvent(
            event_id="",  # Auto-generated by dataclass
            agent_id=agent_id,
            event_type=event_type,
            metadata=metadata
        )

        # Calculate entropy for this event
        event.calculate_entropy()

        # Get or create profile
        profile = self.get_profile(agent_id)

        # Update profile counters based on event type
        if event_type in ("file_read", "file_write", "file_delete", "file_create"):
            profile.file_ops_count += 1
        elif event_type in ("network_request", "network_response", "api_call"):
            profile.network_ops_count += 1

        # Update last activity
        profile.last_activity = datetime.now().isoformat()

        # Add to event history
        if agent_id not in self._event_history:
            self._event_history[agent_id] = []
        self._event_history[agent_id].append(event)

        # Recalculate anomaly score
        profile.entropy_score = self.calculate_anomaly_score(profile)

        # Store updated profile
        self._profiles[agent_id] = profile

        return event

    def get_profile(self, agent_id: str) -> AgentBehavioralProfile:
        """
        Get the behavioral profile for an agent.

        Creates a new profile if one doesn't exist.

        Args:
            agent_id: Unique identifier for the agent

        Returns:
            AgentBehavioralProfile for the agent
        """
        if agent_id not in self._profiles:
            self._profiles[agent_id] = AgentBehavioralProfile(
                agent_id=agent_id,
                file_ops_count=0,
                network_ops_count=0,
                entropy_score=0.0
            )
        return self._profiles[agent_id]

    def calculate_anomaly_score(self, profile: AgentBehavioralProfile) -> float:
        """
        Calculate anomaly score for a profile.

        Uses weighted formula:
        - 40% file operations count (normalized)
        - 30% network operations count (normalized)
        - 30% entropy from recent events

        Args:
            profile: The agent's behavioral profile

        Returns:
            Anomaly score between 0.0 and 1.0
        """
        # Normalize counts to 0.0-1.0 range
        # Using log scale to handle wide ranges
        import math

        # File ops weight: 40%
        # Normalize: log(1 + count) / log(1 + max_expected) where max_expected ~ 100
        file_score = math.log1p(profile.file_ops_count) / math.log1p(100)
        file_score = min(1.0, file_score)

        # Network ops weight: 30%
        network_score = math.log1p(profile.network_ops_count) / math.log1p(100)
        network_score = min(1.0, network_score)

        # Entropy weight: 30% (already normalized 0.0-1.0)
        entropy_score = profile.entropy_score

        # Calculate weighted average
        anomaly_score = (
            0.40 * file_score +
            0.30 * network_score +
            0.30 * entropy_score
        )

        return min(1.0, max(0.0, anomaly_score))

    def is_anomalous(self, agent_id: str) -> bool:
        """
        Check if an agent's behavior is anomalous.

        Args:
            agent_id: Unique identifier for the agent

        Returns:
            True if the agent's anomaly score exceeds the threshold
        """
        profile = self.get_profile(agent_id)
        return profile.entropy_score > self.anomaly_threshold

    def reset_window(self, agent_id: Optional[str] = None) -> None:
        """
        Reset the sliding window for an agent or all agents.

        Clears event history and resets counters for fresh tracking.

        Args:
            agent_id: Specific agent to reset, or None to reset all
        """
        if agent_id is not None:
            # Reset specific agent
            if agent_id in self._profiles:
                self._profiles[agent_id].file_ops_count = 0
                self._profiles[agent_id].network_ops_count = 0
                self._profiles[agent_id].entropy_score = 0.0
                self._profiles[agent_id].sliding_window_start = (
                    datetime.now().isoformat()
                )
            if agent_id in self._event_history:
                self._event_history[agent_id] = []
        else:
            # Reset all agents
            for aid in self._profiles:
                self._profiles[aid].file_ops_count = 0
                self._profiles[aid].network_ops_count = 0
                self._profiles[aid].entropy_score = 0.0
                self._profiles[aid].sliding_window_start = (
                    datetime.now().isoformat()
                )
            self._event_history = {}
