import os
import sys
import json
import subprocess
import argparse

# --- Templates ---

COMMON_HEADER = """// Generated by Geometry OS Synthesis Engine
// Device: {device_name}
// Type: {device_type}

#![no_std]
#![no_main]

use core::arch::global_asm;
use core::panic::PanicInfo;

global_asm!(
    ".section .text.entry",
    ".globl _jit_entry",
    "_jit_entry:",
    "   addi    sp, sp, -16",
    "   sw      ra, 12(sp)",
    "   sw      s0, 8(sp)",
    "   mv      s0, a0",          // mmio_base in s0
    "   jal     ra, jit_driver_main",
    "   lw      ra, 12(sp)",
    "   lw      s0, 8(sp)",
    "   addi    sp, sp, 16",
    "   ret",
);

#[inline(always)]
fn mmio_read(base: u32, offset: u32) -> u32 {{
    unsafe {{ core::ptr::read_volatile((base + offset) as *const u32) }}
}}

#[inline(always)]
fn mmio_write(base: u32, offset: u32, val: u32) {{
    unsafe {{ core::ptr::write_volatile((base + offset) as *mut u32, val) }}
}}

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {{
    loop {{}}
}}
"""

UART_TEMPLATE = """
{common_header}

{registers}

fn uart_putc(base: u32, ch: u8) {{
    while (mmio_read(base, LSR) & LSR_THRE) == 0 {{}}
    mmio_write(base, THR_RBR, ch as u32);
}}

fn uart_print(base: u32, s: &str) {{
    for &b in s.as_bytes() {{
        uart_putc(base, b);
    }}
}}

#[no_mangle]
pub extern "C" fn jit_driver_main(mmio_base: u32) -> u32 {{
    uart_print(mmio_base, "Synthesized {device_name} driver active!\\n");
    0
}}
"""

FB_TEMPLATE = """
{common_header}

const FB_W: u32 = 256;
const FB_H: u32 = 256;

#[no_mangle]
pub extern "C" fn jit_driver_main(fb_base: u32) -> u32 {{
    let mut pixel_count: u32 = 0;
    let color = (0x30 << 24) | (0xE0 << 16) | (0x60 << 8) | 0xFF; // Greenish
    
    for y in 0..FB_H {{
        for x in 0..FB_W {{
            let offset = (y * FB_W + x) * 4;
            unsafe {{
                core::ptr::write_volatile((fb_base + offset) as *mut u32, color);
            }}
            pixel_count += 1;
        }}
    }}
    
    // Flush
    let ctrl = fb_base + FB_W * FB_H * 4;
    unsafe {{
        core::ptr::write_volatile(ctrl as *mut u32, 1);
    }}
    
    pixel_count
}}
"""

VIRTIO_BLK_TEMPLATE = """
{common_header}

{registers}

// VirtIO status bits
const VIRTIO_STATUS_ACKNOWLEDGE: u32 = 1;
const VIRTIO_STATUS_DRIVER: u32 = 2;
const VIRTIO_STATUS_FEATURES_OK: u32 = 8;
const VIRTIO_STATUS_DRIVER_OK: u32 = 4;
const VIRTIO_MAGIC: u32 = 0x74726976;

// Virtqueue constants
const VIRTQ_DESC_F_NEXT: u16 = 1;
const VIRTQ_DESC_F_WRITE: u16 = 2;
const QUEUE_SIZE: u32 = 4;
const VIRTIO_BLK_T_IN: u32 = 0;   // Read
const VIRTIO_BLK_S_OK: u8 = 0;
const SECTOR_SIZE: usize = 512;

// Queue memory layout offsets from QUEUE_MEM_BASE
const OFF_DESC_TABLE: u32 = 0x000;  // 4 entries * 16 bytes = 64 bytes
const OFF_AVAIL_RING: u32 = 0x100;  // flags(2)+idx(2)+ring(4*2)+used_event(2) = 14 bytes
const OFF_USED_RING:   u32 = 0x200;  // flags(2)+idx(2)+ring(4*8)+avail_event(2) = 38 bytes
const OFF_REQ_HEADER:  u32 = 0x400;  // 16 bytes: type(4)+reserved(4)+sector(8)
const OFF_DATA_BUF:    u32 = 0x500;  // 512 bytes for sector data
const OFF_STATUS_BYTE: u32 = 0x800;  // 4 bytes (1 byte status + padding)
const QUEUE_MEM_SIZE: usize = 0x900;  // Total queue memory

// Static queue memory -- lives in BSS, linker zeroes it
#[no_mangle]
static mut QUEUE_MEM: [u8; QUEUE_MEM_SIZE] = [0u8; QUEUE_MEM_SIZE];

// Raw memory access helpers
#[inline(always)]
fn mem_read32(addr: u32) -> u32 {{
    unsafe {{ core::ptr::read_volatile(addr as *const u32) }}
}}

#[inline(always)]
fn mem_write32(addr: u32, val: u32) {{
    unsafe {{ core::ptr::write_volatile(addr as *mut u32, val) }}
}}

#[inline(always)]
fn queue_base() -> u32 {{
    unsafe {{ QUEUE_MEM.as_ptr() as u32 }}
}}

// SBI putchar for diagnostic output
fn sbi_putchar(ch: u8) {{
    unsafe {{
        core::arch::asm!(
            "ecall",
            in("a7") 1u32,
            inout("a0") ch as u32 => _,
            out("a1") _,
            options(nostack),
        );
    }}
}}

fn print_str(s: &str) {{
    for &b in s.as_bytes() {{
        sbi_putchar(b);
    }}
}}

fn print_hex(mut v: u32) {{
    let hex = b"0123456789ABCDEF";
    print_str("0x");
    for i in (0..8).rev() {{
        sbi_putchar(hex[((v >> (i * 4)) & 0xF) as usize]);
    }}
}}

fn print_int(mut n: i32) {{
    if n == 0 {{ sbi_putchar(b'0'); return; }}
    if n < 0 {{ sbi_putchar(b'-'); n = -n; }}
    let mut buf = [0u8; 10];
    let mut i = 0;
    while n > 0 {{
        buf[i] = (n % 10) as u8 + b'0';
        n /= 10;
        i += 1;
    }}
    for j in (0..i).rev() {{
        sbi_putchar(buf[j]);
    }}
}}

#[no_mangle]
pub extern "C" fn jit_driver_main(mmio_base: u32) -> u32 {{
    let qb = queue_base();

    // === Phase 1: Device Init ===

    // 1. Verify magic
    let magic = mmio_read(mmio_base, MagicValue);
    if magic != VIRTIO_MAGIC {{
        return 0xFFFFFFFF;
    }}

    let dev_id = mmio_read(mmio_base, DeviceID);

    // 2. Reset device
    mmio_write(mmio_base, Status, 0);

    // 3. Acknowledge and set driver bit
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE);
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER);

    // 4. Negotiate features (accept all device offers)
    mmio_write(mmio_base, DeviceFeaturesSel, 0);
    let features = mmio_read(mmio_base, DeviceFeatures);
    mmio_write(mmio_base, DriverFeaturesSel, 0);
    mmio_write(mmio_base, DriverFeatures, features);

    // 5. Set FEATURES_OK then DRIVER_OK
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER | VIRTIO_STATUS_FEATURES_OK);
    let status = mmio_read(mmio_base, Status);
    if (status & VIRTIO_STATUS_FEATURES_OK) == 0 {{
        return 0xFFFFFFFE;
    }}
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER | VIRTIO_STATUS_FEATURES_OK | VIRTIO_STATUS_DRIVER_OK);

    // 6. Read config: disk capacity in sectors
    let capacity_lo = mmio_read(mmio_base, Config);

    // === Phase 2: Set up virtqueue ===

    // Select queue 0
    mmio_write(mmio_base, QueueSel, 0);

    // Set queue size
    mmio_write(mmio_base, QueueNum, QUEUE_SIZE);

    // Set descriptor table address
    mmio_write(mmio_base, QueueDescLow, qb + OFF_DESC_TABLE);
    mmio_write(mmio_base, QueueDescHigh, 0);

    // Set available ring address
    mmio_write(mmio_base, QueueAvailLow, qb + OFF_AVAIL_RING);
    mmio_write(mmio_base, QueueAvailHigh, 0);

    // Set used ring address
    mmio_write(mmio_base, QueueUsedLow, qb + OFF_USED_RING);
    mmio_write(mmio_base, QueueUsedHigh, 0);

    // Mark queue ready
    mmio_write(mmio_base, QueueReady, 1);

    // === Phase 3: Build read request for sector 0 ===

    // Request header at OFF_REQ_HEADER: type=READ(0), reserved=0, sector=0
    mem_write32(qb + OFF_REQ_HEADER + 0, VIRTIO_BLK_T_IN);  // type = READ
    mem_write32(qb + OFF_REQ_HEADER + 4, 0);                 // reserved
    mem_write32(qb + OFF_REQ_HEADER + 8, 0);                 // sector lo
    mem_write32(qb + OFF_REQ_HEADER + 12, 0);                // sector hi

    // Descriptor 0: request header (16 bytes, read-only, chained)
    let desc0_addr = qb + OFF_DESC_TABLE;
    mem_write32(desc0_addr + 0, qb + OFF_REQ_HEADER);        // addr lo
    mem_write32(desc0_addr + 4, 0);                           // addr hi
    mem_write32(desc0_addr + 8, 16);                          // len
    mem_write32(desc0_addr + 12, (VIRTQ_DESC_F_NEXT as u32) | (1 << 16)); // flags=NEXT, next=1

    // Descriptor 1: data buffer (512 bytes, writable, chained)
    let desc1_addr = qb + OFF_DESC_TABLE + 16;
    mem_write32(desc1_addr + 0, qb + OFF_DATA_BUF);          // addr lo
    mem_write32(desc1_addr + 4, 0);                           // addr hi
    mem_write32(desc1_addr + 8, SECTOR_SIZE as u32);          // len = 512
    mem_write32(desc1_addr + 12, ((VIRTQ_DESC_F_WRITE | VIRTQ_DESC_F_NEXT) as u32) | (2 << 16)); // flags=WRITE|NEXT, next=2

    // Descriptor 2: status byte (1 byte, writable, no chain)
    let desc2_addr = qb + OFF_DESC_TABLE + 32;
    mem_write32(desc2_addr + 0, qb + OFF_STATUS_BYTE);       // addr lo
    mem_write32(desc2_addr + 4, 0);                           // addr hi
    mem_write32(desc2_addr + 8, 1);                           // len = 1
    mem_write32(desc2_addr + 12, VIRTQ_DESC_F_WRITE as u32); // flags=WRITE, next=0

    // Write 0xFF to status byte so we can detect completion
    mem_write32(qb + OFF_STATUS_BYTE, 0xFF);

    // Available ring: set idx=1 and ring[0]=0 (head descriptor index)
    // Layout: flags(2) | idx(2) | ring[0](2) | ...
    // Write as u32: low half=flags=0, high half=idx=1
    mem_write32(qb + OFF_AVAIL_RING, 1 << 16);  // flags=0, idx=1
    mem_write32(qb + OFF_AVAIL_RING + 4, 0);    // ring[0] = 0 (head desc index)

    // === Phase 4: Kick the queue ===
    mmio_write(mmio_base, QueueNotify, 0);

    // === Phase 5: Poll for completion ===
    // The used ring idx should advance to 1 when the request completes
    let mut timeout = 100000u32;
    let mut completed = false;
    while timeout > 0 {{
        let used_idx = (mem_read32(qb + OFF_USED_RING) >> 16) as u16;
        if used_idx >= 1 {{
            completed = true;
            break;
        }}
        timeout -= 1;
    }}

    if !completed {{
        print_str("BLK: TIMEOUT\\n");
        return 0xFFFFFFFD;
    }}

    // Read status byte
    let blk_status = unsafe {{ *(&QUEUE_MEM[OFF_STATUS_BYTE as usize]) }};

    // Verify data -- first 4 bytes of sector 0 should be readable
    // (Disk is zeroed, so we just check that the read completed successfully)
    let data_word = mem_read32(qb + OFF_DATA_BUF);

    // === Report ===
    print_str("VirtIO BLK: id=");
    print_hex(dev_id);
    print_str(" sectors=");
    print_hex(capacity_lo);
    print_str(" read_status=");
    print_int(blk_status as i32);
    print_str(" data[0:4]=");
    print_hex(data_word);
    print_str(" ok=");
    print_str(if completed {{ "1" }} else {{ "0" }});
    print_str("\\n");

    if blk_status == VIRTIO_BLK_S_OK {{
        0  // Success
    }} else {{
        0xFFFFFFFC  // I/O error
    }}
}}
"""

VIRTIO_NET_TEMPLATE = """
{common_header}

{registers}

// VirtIO status bits
const VIRTIO_STATUS_ACKNOWLEDGE: u32 = 1;
const VIRTIO_STATUS_DRIVER: u32 = 2;
const VIRTIO_STATUS_FEATURES_OK: u32 = 8;
const VIRTIO_STATUS_DRIVER_OK: u32 = 4;
const VIRTIO_MAGIC: u32 = 0x74726976;

// Virtqueue constants
const VIRTQ_DESC_F_NEXT: u16 = 1;
const VIRTQ_DESC_F_WRITE: u16 = 2;
const QUEUE_SIZE: u32 = 4;

// Queue memory layout offsets from QUEUE_MEM_BASE
const OFF_DESC_TABLE: u32 = 0x000;
const OFF_AVAIL_RING: u32 = 0x100;
const OFF_USED_RING:   u32 = 0x200;
const OFF_TX_HEADER:   u32 = 0x400;  // 2-byte VirtIO net header + packet data
const OFF_TX_PACKET:   u32 = 0x402;  // Packet data starts after 2-byte header
const QUEUE_MEM_SIZE: usize = 0x800;

#[no_mangle]
static mut QUEUE_MEM: [u8; QUEUE_MEM_SIZE] = [0u8; QUEUE_MEM_SIZE];

#[inline(always)]
fn mem_read32(addr: u32) -> u32 {{
    unsafe {{ core::ptr::read_volatile(addr as *const u32) }}
}}

#[inline(always)]
fn mem_write32(addr: u32, val: u32) {{
    unsafe {{ core::ptr::write_volatile(addr as *mut u32, val) }}
}}

#[inline(always)]
fn mem_write8(addr: u32, val: u8) {{
    unsafe {{ core::ptr::write_volatile(addr as *mut u8, val) }}
}}

#[inline(always)]
fn queue_base() -> u32 {{
    unsafe {{ QUEUE_MEM.as_ptr() as u32 }}
}}

fn sbi_putchar(ch: u8) {{
    unsafe {{
        core::arch::asm!(
            "ecall",
            in("a7") 1u32,
            inout("a0") ch as u32 => _,
            out("a1") _,
            options(nostack),
        );
    }}
}}

fn print_str(s: &str) {{
    for &b in s.as_bytes() {{
        sbi_putchar(b);
    }}
}}

fn print_hex(mut v: u32) {{
    let hex = b"0123456789ABCDEF";
    print_str("0x");
    for i in (0..8).rev() {{
        sbi_putchar(hex[((v >> (i * 4)) & 0xF) as usize]);
    }}
}}

#[no_mangle]
pub extern "C" fn jit_driver_main(mmio_base: u32) -> u32 {{
    let qb = queue_base();

    // === Phase 1: Device Init ===

    let magic = mmio_read(mmio_base, MagicValue);
    if magic != VIRTIO_MAGIC {{
        return 0xFFFFFFFF;
    }}

    let dev_id = mmio_read(mmio_base, DeviceID);

    // Read MAC from config space
    let mac_lo = mmio_read(mmio_base, Config);
    let mac_hi = mmio_read(mmio_base, 0x104);

    // Reset and init
    mmio_write(mmio_base, Status, 0);
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE);
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER);

    // Negotiate features
    mmio_write(mmio_base, DeviceFeaturesSel, 0);
    let features = mmio_read(mmio_base, DeviceFeatures);
    mmio_write(mmio_base, DriverFeaturesSel, 0);
    mmio_write(mmio_base, DriverFeatures, features);

    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER | VIRTIO_STATUS_FEATURES_OK);
    let status = mmio_read(mmio_base, Status);
    if (status & VIRTIO_STATUS_FEATURES_OK) == 0 {{
        return 0xFFFFFFFE;
    }}
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER | VIRTIO_STATUS_FEATURES_OK | VIRTIO_STATUS_DRIVER_OK);

    // === Phase 2: Set up TX virtqueue (queue 1) ===

    mmio_write(mmio_base, QueueSel, 1);  // TX queue
    mmio_write(mmio_base, QueueNum, QUEUE_SIZE);

    mmio_write(mmio_base, QueueDescLow, qb + OFF_DESC_TABLE);
    mmio_write(mmio_base, QueueDescHigh, 0);
    mmio_write(mmio_base, QueueAvailLow, qb + OFF_AVAIL_RING);
    mmio_write(mmio_base, QueueAvailHigh, 0);
    mmio_write(mmio_base, QueueUsedLow, qb + OFF_USED_RING);
    mmio_write(mmio_base, QueueUsedHigh, 0);
    mmio_write(mmio_base, QueueReady, 1);

    // === Phase 3: Build and send a test packet ===

    // VirtIO net header (2 bytes: flags=0, gso_type=0)
    mem_write8(qb + OFF_TX_HEADER, 0);
    mem_write8(qb + OFF_TX_HEADER + 1, 0);

    // Simple Ethernet frame: dst(6) + src(6) + type(2) + payload
    // Dst: FF:FF:FF:FF:FF:FF (broadcast)
    let pkt_base = qb + OFF_TX_PACKET;
    for i in 0..6u32 {{ mem_write8(pkt_base + i, 0xFF); }}
    // Src: DE:AD:BE:EF:00:01
    let src: [u8; 6] = [0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x01];
    for i in 0..6u32 {{ mem_write8(pkt_base + 6 + i, src[i as usize]); }}
    // EtherType: 0x0800 (IPv4)
    mem_write8(pkt_base + 12, 0x08);
    mem_write8(pkt_base + 13, 0x00);
    // Payload: "GeOS" + padding
    let payload = b"GeOS";
    for (i, &b) in payload.iter().enumerate() {{
        mem_write8(pkt_base + 14 + i as u32, b);
    }}
    // Total packet: 2 (virtio hdr) + 14 (eth header) + 4 (payload) = 20 bytes
    let total_len: u32 = 2 + 14 + 4;

    // Descriptor 0: virtio header + packet (read-only, no chain)
    let desc0_addr = qb + OFF_DESC_TABLE;
    mem_write32(desc0_addr + 0, qb + OFF_TX_HEADER);  // addr lo
    mem_write32(desc0_addr + 4, 0);                     // addr hi
    mem_write32(desc0_addr + 8, total_len);             // len
    mem_write32(desc0_addr + 12, 0);                    // flags=0, next=0

    // Available ring: idx=1, ring[0]=0
    mem_write32(qb + OFF_AVAIL_RING, 1 << 16);  // flags=0, idx=1
    mem_write32(qb + OFF_AVAIL_RING + 4, 0);    // ring[0] = 0

    // === Phase 4: Kick TX queue ===
    mmio_write(mmio_base, QueueNotify, 1);  // queue 1 = TX

    // === Phase 5: Poll for completion ===
    let mut timeout = 100000u32;
    let mut completed = false;
    while timeout > 0 {{
        let used_idx = (mem_read32(qb + OFF_USED_RING) >> 16) as u16;
        if used_idx >= 1 {{
            completed = true;
            break;
        }}
        timeout -= 1;
    }}

    // === Report ===
    print_str("VirtIO NET: id=");
    print_hex(dev_id);
    print_str(" mac=");
    print_hex(mac_lo);
    print_hex(mac_hi);
    print_str(" tx=");
    print_str(if completed {{ "1" }} else {{ "0" }});
    print_str("\\n");

    if completed {{
        0  // Success
    }} else {{
        0xFFFFFFFD  // TX timeout
    }}
}}
"""

def generate_registers(spec):
    regs = []
    for reg in spec.get("registers", []):
        name = reg["name"]
        offset = reg["offset"]
        regs.append(f"const {name}: u32 = {offset};")
        if "bits" in reg:
            for bit_pos, bit_desc in reg["bits"].items():
                bit_name = bit_desc.split(" - ")[0].split(" (")[0]
                mask = 1 << int(bit_pos)
                regs.append(f"const {name}_{bit_name}: u32 = 0x{mask:02X};")
    return "\n".join(regs)

def synthesize(device_type_id, output_elf):
    # Mapping
    specs = {
        0: ("uart_16550.json", UART_TEMPLATE, "jit_driver.ld"),
        1: ("framebuffer.json", FB_TEMPLATE, "jit_driver_fb.ld"),
        2: ("virtio_blk.json", VIRTIO_BLK_TEMPLATE, "jit_driver_virtio_blk.ld"),
        3: ("virtio_net.json", VIRTIO_NET_TEMPLATE, "jit_driver_virtio_net.ld"),
    }
    
    if device_type_id not in specs:
        print(f"Error: Unsupported device type {device_type_id}")
        sys.exit(1)
        
    spec_file, template, ld_script = specs[device_type_id]
    
    # Paths
    base_dir = os.path.dirname(os.path.abspath(__file__))
    spec_path = os.path.join(base_dir, "device_specs", spec_file)
    ld_path = os.path.join(base_dir, ld_script)
    
    with open(spec_path, "r") as f:
        spec = json.load(f)
        
    # Generate source
    registers_code = generate_registers(spec)
    
    header = COMMON_HEADER.format(
        device_name=spec["device_name"],
        device_type=spec["device_type"]
    )
    
    source_code = template.format(
        common_header=header,
        device_name=spec["device_name"],
        registers=registers_code
    )
    
    rs_path = output_elf.replace(".elf", ".rs")
    with open(rs_path, "w") as f:
        f.write(source_code)
        
    # Compile
    cmd = [
        "rustc",
        "--target", "riscv32imac-unknown-none-elf",
        "-C", f"link-arg=-T{ld_path}",
        "-C", "opt-level=z",
        "-C", "panic=abort",
        "-o", output_elf,
        rs_path
    ]
    
    print(f"Compiling synthesized driver: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print("Compilation failed!")
        print(result.stderr)
        sys.exit(1)
        
    print(f"Successfully synthesized {output_elf}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("device_type", type=int)
    parser.add_argument("output_elf")
    args = parser.parse_args()
    
    synthesize(args.device_type, args.output_elf)
