"""
Behavioral tests for forge assembler programs.

Tests import the modules, call their assemble()/forge() functions,
and assert on the returned or generated bytecode sequences.
"""
import struct
import os
import sys

# Add programs directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'programs'))


class TestForgeBoot:
    """Tests for forge_boot.py"""
    
    def test_forge_boot_starts_with_navy_ldi(self):
        """Assert the returned pixel list starts with [0x49, 0, 20] (LDI r0, 20 - navy background color)."""
        from programs.forge_boot import assemble
        pixels = assemble()
        assert pixels[0:3] == [0x49, 0, 20], "Should start with LDI r0, 20 (navy background)"
    
    def test_forge_boot_has_exactly_one_halt(self):
        """Assert the sequence contains exactly one OP_HALT (0x48)."""
        from programs.forge_boot import assemble
        pixels = assemble()
        halt_count = sum(1 for p in pixels if p == 0x48)
        assert halt_count == 1, f"Expected exactly 1 HALT, found {halt_count}"
    
    def test_forge_boot_buffer_length(self):
        """Assert the final buffer is exactly 1024 elements long with zero-padding after HALT."""
        from programs.forge_boot import assemble
        pixels = assemble()
        assert len(pixels) == 1024, f"Expected 1024 elements, got {len(pixels)}"
        # Find HALT position
        halt_idx = pixels.index(0x48)
        # All elements after HALT should be 0
        for i in range(halt_idx + 1, 1024):
            assert pixels[i] == 0, f"Expected zero padding at index {i}, got {pixels[i]}"
    
    def test_forge_boot_rectf_count(self):
        """Count the number of RECTF (0x46) opcodes and assert it equals expected rectangles."""
        from programs.forge_boot import assemble
        pixels = assemble()
        rectf_count = sum(1 for p in pixels if p == 0x46)
        # Background (1) + Taskbar (1) + G letter (4 parts: top, left, bottom, right notch)
        expected_rectf = 6
        assert rectf_count == expected_rectf, f"Expected {expected_rectf} RECTF, found {rectf_count}"


class TestForgePaintGeos:
    """Tests for forge_paint_geos.py"""
    
    def test_forge_paint_geos_edit_overwrite_operands(self):
        """Assert each EDIT_OVERWRITE (0x65) instruction has correct register operands."""
        from programs.forge_paint_geos import assemble
        pixels = assemble()
        
        # Find all EDIT_OVERWRITE instructions (0x65)
        edit_ovw_indices = [i for i, p in enumerate(pixels) if p == 0x65]
        assert len(edit_ovw_indices) == 4, f"Expected 4 EDIT_OVERWRITE, found {len(edit_ovw_indices)}"
        
        # Each EDIT_OVERWRITE should be followed by [0, 1] (r0, r1)
        for idx in edit_ovw_indices:
            assert pixels[idx + 1] == 0, f"EDIT_OVERWRITE at {idx} should have r0 operand"
            assert pixels[idx + 2] == 1, f"EDIT_OVERWRITE at {idx} should have r1 operand"
    
    def test_forge_paint_geos_character_values(self):
        """Verify the character values written match ord('G'), ord('E'), ord('O'), ord('S')."""
        from programs.forge_paint_geos import assemble
        pixels = assemble()
        
        expected_chars = [ord('G'), ord('E'), ord('O'), ord('S')]
        char_values = []
        
        i = 0
        while i < len(pixels) and len(char_values) < 4:
            if pixels[i] == 0x49:  # LDI
                if i + 2 < len(pixels) and pixels[i + 1] == 1:  # LDI r1, value
                    char_values.append(pixels[i + 2])
                    i += 3
                else:
                    i += 3
            else:
                i += 1
        
        assert char_values == expected_chars, f"Expected {expected_chars}, got {char_values}"


class TestForgeFont:
    """Tests for forge_font.py"""
    
    def test_forge_font_dictionary_size(self):
        """Assert len(FONT) >= 22."""
        from programs.forge_font import FONT
        assert len(FONT) >= 22, f"Expected at least 22 font entries, got {len(FONT)}"
    
    def test_forge_font_values_are_integers(self):
        """Assert each value is an integer."""
        from programs.forge_font import FONT
        for char, value in FONT.items():
            assert isinstance(value, int), f"FONT['{char}'] should be int, got {type(value)}"
    
    def test_forge_font_A_value(self):
        """Assert FONT['A'] == 0b111101111101101."""
        from programs.forge_font import FONT
        assert FONT['A'] == 0b111101111101101, f"FONT['A'] mismatch"
    
    def test_forge_font_E_pixel_pattern(self):
        """Verify the pixel pattern for 'E' matches expected rows."""
        from programs.forge_font import FONT, get_pixel
        
        # Expected pattern for 'E' in 3x5 grid (row-major, bit 0 is top-left)
        # Row 0: [1, 1, 1] - top bar
        # Row 1: [1, 0, 0] - left side
        # Row 2: [1, 1, 1] - middle bar
        # Row 3: [1, 0, 0] - left side
        # Row 4: [1, 1, 1] - bottom bar
        # Expected pattern for 'E' based on FONT['E'] = 0b111010111011111
        # Bit layout: bit 0 is top-left, bit 14 is bottom-right (row-major)
        # Binary: 111010111011111 (15 bits)
        # Bits from right (0) to left (14): 1,1,1,1,1,0,1,1,1,0,1,0,1,1,1
        expected_rows = [
            [1, 1, 1],  # row 0: bits 0,1,2 = 111
            [1, 1, 0],  # row 1: bits 3,4,5 = 110
            [1, 1, 1],  # row 2: bits 6,7,8 = 111
            [0, 1, 0],  # row 3: bits 9,10,11 = 010
            [1, 1, 1],  # row 4: bits 12,13,14 = 111
        ]
        
        mask = FONT['E']
        for row in range(5):
            for col in range(3):
                actual_pixel = get_pixel(mask, col, row)
                expected_pixel = expected_rows[row][col]
                assert actual_pixel == expected_pixel, \
                    f"FONT['E'] row {row} col {col}: expected {expected_pixel}, got {actual_pixel}"


class TestForgeMovingPixel:
    """Tests for forge_moving_pixel.py"""
    
    def test_forge_moving_pixel_has_branch_and_jmp(self):
        """Verify the program's opcode stream contains BRANCH (0x42) and JMP (0x4A) instructions."""
        from programs.forge_moving_pixel import assemble
        pixels = assemble()
        
        has_branch = any(p == 0x42 for p in pixels)
        has_jmp = any(p == 0x4A for p in pixels)
        
        assert has_branch, "Program should contain BRANCH (0x42) instructions"
        assert has_jmp, "Program should contain JMP (0x4A) instructions"
    
    def test_forge_moving_pixel_initial_register_setup(self):
        """Verify the initial register setup sets r1=128, r2=128 (starting position)."""
        from programs.forge_moving_pixel import assemble
        pixels = assemble()
        
        # First two LDI instructions should set r1=128 and r2=128
        # LDI is 0x49, format: [OP_LDI, reg, value]
        assert pixels[0] == 0x49, "First instruction should be LDI"
        assert pixels[1] == 1, "First LDI should target r1"
        assert pixels[2] == 128, "First LDI should set r1=128"
        
        assert pixels[3] == 0x49, "Fourth instruction should be LDI"
        assert pixels[4] == 2, "Second LDI should target r2"
        assert pixels[5] == 128, "Second LDI should set r2=128"
    
    def test_forge_moving_pixel_buffer_length(self):
        """Verify the buffer is 1024 elements."""
        from programs.forge_moving_pixel import assemble
        pixels = assemble()
        assert len(pixels) == 1024, f"Expected 1024 elements, got {len(pixels)}"
