/**
 * Neural City WASM Module - JavaScript Wrapper
 *
 * Provides a high-level API for the WASM simulation.
 * Falls back to JavaScript implementation if WASM not available.
 */

// Import WASM module (generated by wasm-pack)
// import init, { NeuralCityWasm } from './pkg/neural_city_wasm.js';

/**
 * Guild types matching Rust/WASM
 */
const Guild = {
    ATTENTION: 0,
    MEMORY: 1,
    LOGIC: 2,
    SUBSTRATE: 3,
    INTENT: 4
};

/**
 * Citizen states matching Rust/WASM
 */
const State = {
    DORMANT: 0,
    ACTIVE: 1,
    TRADING: 2,
    MIGRATING: 3,
    REPRODUCING: 4,
    DECLINING: 5,
    DEAD: 6
};

/**
 * High-performance Neural City simulation.
 * Uses WASM when available, falls back to JS.
 */
class NeuralCity {
    constructor(width, height, useWasm = true) {
        this.width = width;
        this.height = height;
        this.wasm = null;
        this.useWasm = useWasm;
        this.ready = false;

        // Fallback JS implementation
        this.citizens = new Map();
        this.nextId = 1;
        this.tickCount = 0;

        // Spatial index (JS fallback)
        this.cellSize = 64;
        this.cells = new Map();
        this.positions = new Map();

        // Performance tracking
        this.metrics = {
            totalTicks: 0,
            avgTickMs: 0,
            fps: 0
        };
    }

    /**
     * Initialize WASM module
     */
    async initWasm() {
        if (!this.useWasm) {
            this.ready = true;
            return false;
        }

        try {
            // Dynamic import of WASM module
            const wasmModule = await import('./pkg/neural_city_wasm.js');
            await wasmModule.default();
            this.wasm = new wasmModule.NeuralCityWasm(this.width, this.height);
            this.ready = true;
            console.log('Neural City WASM initialized');
            return true;
        } catch (err) {
            console.warn('WASM not available, using JS fallback:', err.message);
            this.ready = true;
            return false;
        }
    }

    /**
     * Add a citizen
     */
    addCitizen(x, y, guild) {
        if (this.wasm) {
            return this.wasm.add_citizen(x, y, guild);
        }

        const id = this.nextId++;
        const citizen = {
            id,
            x,
            y,
            vx: 0,
            vy: 0,
            energy: 1.0,
            entropy: 0,
            guild,
            state: State.ACTIVE,
            generation: 0,
            territoryRadius: 16
        };

        this.citizens.set(id, citizen);
        this._insertSpatial(id, x, y);

        return id;
    }

    /**
     * Remove a citizen
     */
    removeCitizen(id) {
        if (this.wasm) {
            this.wasm.remove_citizen(id);
            return;
        }

        this.citizens.delete(id);
        this._removeSpatial(id);
    }

    /**
     * Get citizen count
     */
    count() {
        if (this.wasm) {
            return this.wasm.count();
        }
        return this.citizens.size;
    }

    /**
     * Run simulation tick
     */
    tick() {
        const start = performance.now();

        let result;

        if (this.wasm) {
            result = this.wasm.tick();
            result = {
                tick: result.tick,
                population: result.population,
                movements: result.movements,
                trades: result.trades,
                births: result.births,
                deaths: result.deaths,
                elapsedMs: result.elapsed_us / 1000
            };
        } else {
            result = this._tickJS();
        }

        const elapsed = performance.now() - start;

        // Update metrics
        this.metrics.totalTicks++;
        this.metrics.avgTickMs = (this.metrics.avgTickMs * 0.9) + (elapsed * 0.1);
        this.metrics.fps = 1000 / this.metrics.avgTickMs;

        return result;
    }

    /**
     * JavaScript fallback tick implementation
     */
    _tickJS() {
        const result = {
            tick: ++this.tickCount,
            population: this.citizens.size,
            movements: 0,
            trades: 0,
            births: 0,
            deaths: 0,
            elapsedMs: 0
        };

        // Rebuild spatial index
        this._rebuildSpatialIndex();

        // Process each citizen
        const deadIds = [];

        for (const [id, citizen] of this.citizens) {
            if (citizen.state === State.DEAD) {
                deadIds.push(id);
                continue;
            }

            // Movement
            if (citizen.state === State.ACTIVE) {
                citizen.vx = (Math.random() - 0.5) * 4;
                citizen.vy = (Math.random() - 0.5) * 4;

                citizen.x = Math.max(0, Math.min(this.width - 1, citizen.x + citizen.vx));
                citizen.y = Math.max(0, Math.min(this.height - 1, citizen.y + citizen.vy));

                result.movements++;
            }

            // Trading
            if (citizen.state === State.ACTIVE && citizen.energy > 0.3) {
                const neighbors = this._queryNearby(citizen.x, citizen.y, 64);

                for (const neighborId of neighbors) {
                    if (neighborId === id) continue;

                    const neighbor = this.citizens.get(neighborId);
                    if (!neighbor || neighbor.guild === citizen.guild) continue;

                    const diff = citizen.energy - neighbor.energy;
                    if (Math.abs(diff) > 0.1) {
                        const amount = Math.abs(diff) * 0.1;
                        if (diff > 0) {
                            citizen.energy -= amount;
                            neighbor.energy += amount * 0.9;
                        }
                        result.trades++;
                        break;
                    }
                }
            }

            // Energy decay
            citizen.energy *= 0.999;

            // Death check
            if (citizen.energy < 0.01) {
                citizen.state = State.DEAD;
                result.deaths++;
            }
        }

        // Remove dead
        for (const id of deadIds) {
            this.citizens.delete(id);
            this._removeSpatial(id);
        }

        return result;
    }

    /**
     * Get all citizens as array
     */
    getCitizens() {
        if (this.wasm) {
            const json = this.wasm.get_citizens_json();
            return JSON.parse(json);
        }
        return Array.from(this.citizens.values());
    }

    /**
     * Get citizens in a region
     */
    getCitizensInRegion(x, y, radius) {
        if (this.wasm) {
            return this.wasm.get_citizens_in_region(x, y, radius);
        }
        return this._queryNearby(x, y, radius);
    }

    // Spatial index methods (JS fallback)

    _cellKey(cx, cy) {
        const cols = Math.ceil(this.width / this.cellSize);
        return cy * cols + cx;
    }

    _getCellCoords(x, y) {
        const cols = Math.ceil(this.width / this.cellSize);
        const rows = Math.ceil(this.height / this.cellSize);
        const cx = Math.min(Math.floor(x / this.cellSize), cols - 1);
        const cy = Math.min(Math.floor(y / this.cellSize), rows - 1);
        return [cx, cy];
    }

    _insertSpatial(id, x, y) {
        const [cx, cy] = this._getCellCoords(x, y);
        const key = this._cellKey(cx, cy);

        if (!this.cells.has(key)) {
            this.cells.set(key, new Set());
        }
        this.cells.get(key).add(id);
        this.positions.set(id, [x, y]);
    }

    _removeSpatial(id) {
        const pos = this.positions.get(id);
        if (pos) {
            const [cx, cy] = this._getCellCoords(pos[0], pos[1]);
            const key = this._cellKey(cx, cy);
            const cell = this.cells.get(key);
            if (cell) {
                cell.delete(id);
            }
            this.positions.delete(id);
        }
    }

    _rebuildSpatialIndex() {
        this.cells.clear();
        for (const [id, citizen] of this.citizens) {
            this._insertSpatial(id, citizen.x, citizen.y);
        }
    }

    _queryNearby(x, y, radius) {
        const results = [];
        const radiusSq = radius * radius;

        const cols = Math.ceil(this.width / this.cellSize);
        const rows = Math.ceil(this.height / this.cellSize);

        const minCx = Math.max(0, Math.floor((x - radius) / this.cellSize));
        const maxCx = Math.min(cols - 1, Math.floor((x + radius) / this.cellSize));
        const minCy = Math.max(0, Math.floor((y - radius) / this.cellSize));
        const maxCy = Math.min(rows - 1, Math.floor((y + radius) / this.cellSize));

        for (let cy = minCy; cy <= maxCy; cy++) {
            for (let cx = minCx; cx <= maxCx; cx++) {
                const key = this._cellKey(cx, cy);
                const cell = this.cells.get(key);

                if (cell) {
                    for (const id of cell) {
                        const pos = this.positions.get(id);
                        if (pos) {
                            const dx = pos[0] - x;
                            const dy = pos[1] - y;
                            if (dx * dx + dy * dy <= radiusSq) {
                                results.push(id);
                            }
                        }
                    }
                }
            }
        }

        return results;
    }

    /**
     * Get performance metrics
     */
    getMetrics() {
        return { ...this.metrics };
    }
}

// Export for different module systems
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { NeuralCity, Guild, State };
}

if (typeof window !== 'undefined') {
    window.NeuralCity = NeuralCity;
    window.NeuralCityGuild = Guild;
    window.NeuralCityState = State;
}

export { NeuralCity, Guild, State };
