
// Generated by Geometry OS Synthesis Engine
// Device: Geometry OS Framebuffer
// Type: display

#![no_std]
#![no_main]

use core::arch::global_asm;
use core::panic::PanicInfo;

global_asm!(
    ".section .text.entry",
    ".globl _jit_entry",
    "_jit_entry:",
    "   addi    sp, sp, -16",
    "   sw      ra, 12(sp)",
    "   sw      s0, 8(sp)",
    "   mv      s0, a0",          // mmio_base in s0
    "   jal     ra, jit_driver_main",
    "   lw      ra, 12(sp)",
    "   lw      s0, 8(sp)",
    "   addi    sp, sp, 16",
    "   ret",
);

#[inline(always)]
fn mmio_read(base: u32, offset: u32) -> u32 {
    unsafe { core::ptr::read_volatile((base + offset) as *const u32) }
}

#[inline(always)]
fn mmio_write(base: u32, offset: u32, val: u32) {
    unsafe { core::ptr::write_volatile((base + offset) as *mut u32, val) }
}

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}


const FB_W: u32 = 256;
const FB_H: u32 = 256;

#[no_mangle]
pub extern "C" fn jit_driver_main(fb_base: u32) -> u32 {
    let mut pixel_count: u32 = 0;
    let color = (0x30 << 24) | (0xE0 << 16) | (0x60 << 8) | 0xFF; // Greenish
    
    for y in 0..FB_H {
        for x in 0..FB_W {
            let offset = (y * FB_W + x) * 4;
            unsafe {
                core::ptr::write_volatile((fb_base + offset) as *mut u32, color);
            }
            pixel_count += 1;
        }
    }
    
    // Flush
    let ctrl = fb_base + FB_W * FB_H * 4;
    unsafe {
        core::ptr::write_volatile(ctrl as *mut u32, 1);
    }
    
    pixel_count
}
