
// Generated by Geometry OS Synthesis Engine
// Device: NS16550A UART
// Type: serial_port

#![no_std]
#![no_main]

use core::arch::global_asm;
use core::panic::PanicInfo;

global_asm!(
    ".section .text.entry",
    ".globl _jit_entry",
    "_jit_entry:",
    "   addi    sp, sp, -16",
    "   sw      ra, 12(sp)",
    "   sw      s0, 8(sp)",
    "   mv      s0, a0",          // mmio_base in s0
    "   jal     ra, jit_driver_main",
    "   lw      ra, 12(sp)",
    "   lw      s0, 8(sp)",
    "   addi    sp, sp, 16",
    "   ret",
);

#[inline(always)]
fn mmio_read(base: u32, offset: u32) -> u32 {
    unsafe { core::ptr::read_volatile((base + offset) as *const u32) }
}

#[inline(always)]
fn mmio_write(base: u32, offset: u32, val: u32) {
    unsafe { core::ptr::write_volatile((base + offset) as *mut u32, val) }
}

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}


const THR_RBR: u32 = 0x00;
const IER: u32 = 0x01;
const IER_ERBI: u32 = 0x01;
const IER_ETBEI: u32 = 0x02;
const IER_ELSI: u32 = 0x04;
const IER_EDSSI: u32 = 0x08;
const IIR_FCR: u32 = 0x02;
const LCR: u32 = 0x03;
const LCR_DLAB: u32 = 0x80;
const MCR: u32 = 0x04;
const LSR: u32 = 0x05;
const LSR_DR: u32 = 0x01;
const LSR_THRE: u32 = 0x20;
const MSR: u32 = 0x06;
const SCR: u32 = 0x07;

fn uart_putc(base: u32, ch: u8) {
    while (mmio_read(base, LSR) & LSR_THRE) == 0 {}
    mmio_write(base, THR_RBR, ch as u32);
}

fn uart_print(base: u32, s: &str) {
    for &b in s.as_bytes() {
        uart_putc(base, b);
    }
}

#[no_mangle]
pub extern "C" fn jit_driver_main(mmio_base: u32) -> u32 {
    uart_print(mmio_base, "Synthesized NS16550A UART driver active!\n");
    0
}
