
// Generated by Geometry OS Synthesis Engine
// Device: Virtio Network Device
// Type: network

#![no_std]
#![no_main]

use core::arch::global_asm;
use core::panic::PanicInfo;

global_asm!(
    ".section .text.entry",
    ".globl _jit_entry",
    "_jit_entry:",
    "   addi    sp, sp, -16",
    "   sw      ra, 12(sp)",
    "   sw      s0, 8(sp)",
    "   mv      s0, a0",          // mmio_base in s0
    "   jal     ra, jit_driver_main",
    "   lw      ra, 12(sp)",
    "   lw      s0, 8(sp)",
    "   addi    sp, sp, 16",
    "   ret",
);

#[inline(always)]
fn mmio_read(base: u32, offset: u32) -> u32 {
    unsafe { core::ptr::read_volatile((base + offset) as *const u32) }
}

#[inline(always)]
fn mmio_write(base: u32, offset: u32, val: u32) {
    unsafe { core::ptr::write_volatile((base + offset) as *mut u32, val) }
}

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}


const MagicValue: u32 = 0x00;
const Version: u32 = 0x04;
const DeviceID: u32 = 0x08;
const VendorID: u32 = 0x0C;
const DeviceFeatures: u32 = 0x10;
const DeviceFeaturesSel: u32 = 0x14;
const DriverFeatures: u32 = 0x20;
const DriverFeaturesSel: u32 = 0x24;
const Status: u32 = 0x28;
const QueueSel: u32 = 0x30;
const QueueNumMax: u32 = 0x34;
const QueueNum: u32 = 0x38;
const QueueReady: u32 = 0x44;
const QueueDescLow: u32 = 0x48;
const QueueDescHigh: u32 = 0x4C;
const QueueAvailLow: u32 = 0x50;
const QueueAvailHigh: u32 = 0x54;
const QueueUsedLow: u32 = 0x58;
const QueueUsedHigh: u32 = 0x5C;
const QueueNotify: u32 = 0x60;
const InterruptACK: u32 = 0x64;
const InterruptStatus: u32 = 0x70;
const ConfigGeneration: u32 = 0x80;
const Config: u32 = 0x100;

// VirtIO status bits
const VIRTIO_STATUS_ACKNOWLEDGE: u32 = 1;
const VIRTIO_STATUS_DRIVER: u32 = 2;
const VIRTIO_STATUS_FEATURES_OK: u32 = 8;
const VIRTIO_STATUS_DRIVER_OK: u32 = 4;
const VIRTIO_MAGIC: u32 = 0x74726976;

// Virtqueue constants
const VIRTQ_DESC_F_NEXT: u16 = 1;
const VIRTQ_DESC_F_WRITE: u16 = 2;
const QUEUE_SIZE: u32 = 4;

// Queue memory layout offsets from QUEUE_MEM_BASE
const OFF_DESC_TABLE: u32 = 0x000;
const OFF_AVAIL_RING: u32 = 0x100;
const OFF_USED_RING:   u32 = 0x200;
const OFF_TX_HEADER:   u32 = 0x400;  // 2-byte VirtIO net header + packet data
const OFF_TX_PACKET:   u32 = 0x402;  // Packet data starts after 2-byte header
const QUEUE_MEM_SIZE: usize = 0x800;

#[no_mangle]
static mut QUEUE_MEM: [u8; QUEUE_MEM_SIZE] = [0u8; QUEUE_MEM_SIZE];

#[inline(always)]
fn mem_read32(addr: u32) -> u32 {
    unsafe { core::ptr::read_volatile(addr as *const u32) }
}

#[inline(always)]
fn mem_write32(addr: u32, val: u32) {
    unsafe { core::ptr::write_volatile(addr as *mut u32, val) }
}

#[inline(always)]
fn mem_write8(addr: u32, val: u8) {
    unsafe { core::ptr::write_volatile(addr as *mut u8, val) }
}

#[inline(always)]
fn queue_base() -> u32 {
    unsafe { QUEUE_MEM.as_ptr() as u32 }
}

fn sbi_putchar(ch: u8) {
    unsafe {
        core::arch::asm!(
            "ecall",
            in("a7") 1u32,
            inout("a0") ch as u32 => _,
            out("a1") _,
            options(nostack),
        );
    }
}

fn print_str(s: &str) {
    for &b in s.as_bytes() {
        sbi_putchar(b);
    }
}

fn print_hex(mut v: u32) {
    let hex = b"0123456789ABCDEF";
    print_str("0x");
    for i in (0..8).rev() {
        sbi_putchar(hex[((v >> (i * 4)) & 0xF) as usize]);
    }
}

#[no_mangle]
pub extern "C" fn jit_driver_main(mmio_base: u32) -> u32 {
    let qb = queue_base();

    // === Phase 1: Device Init ===

    let magic = mmio_read(mmio_base, MagicValue);
    if magic != VIRTIO_MAGIC {
        return 0xFFFFFFFF;
    }

    let dev_id = mmio_read(mmio_base, DeviceID);

    // Read MAC from config space
    let mac_lo = mmio_read(mmio_base, Config);
    let mac_hi = mmio_read(mmio_base, 0x104);

    // Reset and init
    mmio_write(mmio_base, Status, 0);
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE);
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER);

    // Negotiate features
    mmio_write(mmio_base, DeviceFeaturesSel, 0);
    let features = mmio_read(mmio_base, DeviceFeatures);
    mmio_write(mmio_base, DriverFeaturesSel, 0);
    mmio_write(mmio_base, DriverFeatures, features);

    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER | VIRTIO_STATUS_FEATURES_OK);
    let status = mmio_read(mmio_base, Status);
    if (status & VIRTIO_STATUS_FEATURES_OK) == 0 {
        return 0xFFFFFFFE;
    }
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER | VIRTIO_STATUS_FEATURES_OK | VIRTIO_STATUS_DRIVER_OK);

    // === Phase 2: Set up TX virtqueue (queue 1) ===

    mmio_write(mmio_base, QueueSel, 1);  // TX queue
    mmio_write(mmio_base, QueueNum, QUEUE_SIZE);

    mmio_write(mmio_base, QueueDescLow, qb + OFF_DESC_TABLE);
    mmio_write(mmio_base, QueueDescHigh, 0);
    mmio_write(mmio_base, QueueAvailLow, qb + OFF_AVAIL_RING);
    mmio_write(mmio_base, QueueAvailHigh, 0);
    mmio_write(mmio_base, QueueUsedLow, qb + OFF_USED_RING);
    mmio_write(mmio_base, QueueUsedHigh, 0);
    mmio_write(mmio_base, QueueReady, 1);

    // === Phase 3: Build and send a test packet ===

    // VirtIO net header (2 bytes: flags=0, gso_type=0)
    mem_write8(qb + OFF_TX_HEADER, 0);
    mem_write8(qb + OFF_TX_HEADER + 1, 0);

    // Simple Ethernet frame: dst(6) + src(6) + type(2) + payload
    // Dst: FF:FF:FF:FF:FF:FF (broadcast)
    let pkt_base = qb + OFF_TX_PACKET;
    for i in 0..6u32 { mem_write8(pkt_base + i, 0xFF); }
    // Src: DE:AD:BE:EF:00:01
    let src: [u8; 6] = [0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x01];
    for i in 0..6u32 { mem_write8(pkt_base + 6 + i, src[i as usize]); }
    // EtherType: 0x0800 (IPv4)
    mem_write8(pkt_base + 12, 0x08);
    mem_write8(pkt_base + 13, 0x00);
    // Payload: "GeOS" + padding
    let payload = b"GeOS";
    for (i, &b) in payload.iter().enumerate() {
        mem_write8(pkt_base + 14 + i as u32, b);
    }
    // Total packet: 2 (virtio hdr) + 14 (eth header) + 4 (payload) = 20 bytes
    let total_len: u32 = 2 + 14 + 4;

    // Descriptor 0: virtio header + packet (read-only, no chain)
    let desc0_addr = qb + OFF_DESC_TABLE;
    mem_write32(desc0_addr + 0, qb + OFF_TX_HEADER);  // addr lo
    mem_write32(desc0_addr + 4, 0);                     // addr hi
    mem_write32(desc0_addr + 8, total_len);             // len
    mem_write32(desc0_addr + 12, 0);                    // flags=0, next=0

    // Available ring: idx=1, ring[0]=0
    mem_write32(qb + OFF_AVAIL_RING, 1 << 16);  // flags=0, idx=1
    mem_write32(qb + OFF_AVAIL_RING + 4, 0);    // ring[0] = 0

    // === Phase 4: Kick TX queue ===
    mmio_write(mmio_base, QueueNotify, 1);  // queue 1 = TX

    // === Phase 5: Poll for completion ===
    let mut timeout = 100000u32;
    let mut completed = false;
    while timeout > 0 {
        let used_idx = (mem_read32(qb + OFF_USED_RING) >> 16) as u16;
        if used_idx >= 1 {
            completed = true;
            break;
        }
        timeout -= 1;
    }

    // === Report ===
    print_str("VirtIO NET: id=");
    print_hex(dev_id);
    print_str(" mac=");
    print_hex(mac_lo);
    print_hex(mac_hi);
    print_str(" tx=");
    print_str(if completed { "1" } else { "0" });
    print_str("\n");

    if completed {
        0  // Success
    } else {
        0xFFFFFFFD  // TX timeout
    }
}
