
// Generated by Geometry OS Synthesis Engine
// Device: Virtio Block Device
// Type: block_storage

#![no_std]
#![no_main]

use core::arch::global_asm;
use core::panic::PanicInfo;

global_asm!(
    ".section .text.entry",
    ".globl _jit_entry",
    "_jit_entry:",
    "   addi    sp, sp, -16",
    "   sw      ra, 12(sp)",
    "   sw      s0, 8(sp)",
    "   mv      s0, a0",          // mmio_base in s0
    "   jal     ra, jit_driver_main",
    "   lw      ra, 12(sp)",
    "   lw      s0, 8(sp)",
    "   addi    sp, sp, 16",
    "   ret",
);

#[inline(always)]
fn mmio_read(base: u32, offset: u32) -> u32 {
    unsafe { core::ptr::read_volatile((base + offset) as *const u32) }
}

#[inline(always)]
fn mmio_write(base: u32, offset: u32, val: u32) {
    unsafe { core::ptr::write_volatile((base + offset) as *mut u32, val) }
}

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}


const MagicValue: u32 = 0x00;
const Version: u32 = 0x04;
const DeviceID: u32 = 0x08;
const VendorID: u32 = 0x0C;
const DeviceFeatures: u32 = 0x10;
const DeviceFeaturesSel: u32 = 0x14;
const DriverFeatures: u32 = 0x20;
const DriverFeaturesSel: u32 = 0x24;
const Status: u32 = 0x28;
const QueueSel: u32 = 0x30;
const QueueNumMax: u32 = 0x34;
const QueueNum: u32 = 0x38;
const QueueReady: u32 = 0x44;
const QueueDescLow: u32 = 0x48;
const QueueDescHigh: u32 = 0x4C;
const QueueAvailLow: u32 = 0x50;
const QueueAvailHigh: u32 = 0x54;
const QueueUsedLow: u32 = 0x58;
const QueueUsedHigh: u32 = 0x5C;
const QueueNotify: u32 = 0x60;
const InterruptACK: u32 = 0x64;
const InterruptStatus: u32 = 0x70;
const ConfigGeneration: u32 = 0x80;
const Config: u32 = 0x100;

// VirtIO status bits
const VIRTIO_STATUS_ACKNOWLEDGE: u32 = 1;
const VIRTIO_STATUS_DRIVER: u32 = 2;
const VIRTIO_STATUS_FEATURES_OK: u32 = 8;
const VIRTIO_STATUS_DRIVER_OK: u32 = 4;
const VIRTIO_MAGIC: u32 = 0x74726976;

// Virtqueue constants
const VIRTQ_DESC_F_NEXT: u16 = 1;
const VIRTQ_DESC_F_WRITE: u16 = 2;
const QUEUE_SIZE: u32 = 4;
const VIRTIO_BLK_T_IN: u32 = 0;   // Read
const VIRTIO_BLK_S_OK: u8 = 0;
const SECTOR_SIZE: usize = 512;

// Queue memory layout offsets from QUEUE_MEM_BASE
const OFF_DESC_TABLE: u32 = 0x000;  // 4 entries * 16 bytes = 64 bytes
const OFF_AVAIL_RING: u32 = 0x100;  // flags(2)+idx(2)+ring(4*2)+used_event(2) = 14 bytes
const OFF_USED_RING:   u32 = 0x200;  // flags(2)+idx(2)+ring(4*8)+avail_event(2) = 38 bytes
const OFF_REQ_HEADER:  u32 = 0x400;  // 16 bytes: type(4)+reserved(4)+sector(8)
const OFF_DATA_BUF:    u32 = 0x500;  // 512 bytes for sector data
const OFF_STATUS_BYTE: u32 = 0x800;  // 4 bytes (1 byte status + padding)
const QUEUE_MEM_SIZE: usize = 0x900;  // Total queue memory

// Static queue memory -- lives in BSS, linker zeroes it
#[no_mangle]
static mut QUEUE_MEM: [u8; QUEUE_MEM_SIZE] = [0u8; QUEUE_MEM_SIZE];

// Raw memory access helpers
#[inline(always)]
fn mem_read32(addr: u32) -> u32 {
    unsafe { core::ptr::read_volatile(addr as *const u32) }
}

#[inline(always)]
fn mem_write32(addr: u32, val: u32) {
    unsafe { core::ptr::write_volatile(addr as *mut u32, val) }
}

#[inline(always)]
fn queue_base() -> u32 {
    unsafe { QUEUE_MEM.as_ptr() as u32 }
}

// SBI putchar for diagnostic output
fn sbi_putchar(ch: u8) {
    unsafe {
        core::arch::asm!(
            "ecall",
            in("a7") 1u32,
            inout("a0") ch as u32 => _,
            out("a1") _,
            options(nostack),
        );
    }
}

fn print_str(s: &str) {
    for &b in s.as_bytes() {
        sbi_putchar(b);
    }
}

fn print_hex(mut v: u32) {
    let hex = b"0123456789ABCDEF";
    print_str("0x");
    for i in (0..8).rev() {
        sbi_putchar(hex[((v >> (i * 4)) & 0xF) as usize]);
    }
}

fn print_int(mut n: i32) {
    if n == 0 { sbi_putchar(b'0'); return; }
    if n < 0 { sbi_putchar(b'-'); n = -n; }
    let mut buf = [0u8; 10];
    let mut i = 0;
    while n > 0 {
        buf[i] = (n % 10) as u8 + b'0';
        n /= 10;
        i += 1;
    }
    for j in (0..i).rev() {
        sbi_putchar(buf[j]);
    }
}

#[no_mangle]
pub extern "C" fn jit_driver_main(mmio_base: u32) -> u32 {
    let qb = queue_base();

    // === Phase 1: Device Init ===

    // 1. Verify magic
    let magic = mmio_read(mmio_base, MagicValue);
    if magic != VIRTIO_MAGIC {
        return 0xFFFFFFFF;
    }

    let dev_id = mmio_read(mmio_base, DeviceID);

    // 2. Reset device
    mmio_write(mmio_base, Status, 0);

    // 3. Acknowledge and set driver bit
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE);
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER);

    // 4. Negotiate features (accept all device offers)
    mmio_write(mmio_base, DeviceFeaturesSel, 0);
    let features = mmio_read(mmio_base, DeviceFeatures);
    mmio_write(mmio_base, DriverFeaturesSel, 0);
    mmio_write(mmio_base, DriverFeatures, features);

    // 5. Set FEATURES_OK then DRIVER_OK
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER | VIRTIO_STATUS_FEATURES_OK);
    let status = mmio_read(mmio_base, Status);
    if (status & VIRTIO_STATUS_FEATURES_OK) == 0 {
        return 0xFFFFFFFE;
    }
    mmio_write(mmio_base, Status, VIRTIO_STATUS_ACKNOWLEDGE | VIRTIO_STATUS_DRIVER | VIRTIO_STATUS_FEATURES_OK | VIRTIO_STATUS_DRIVER_OK);

    // 6. Read config: disk capacity in sectors
    let capacity_lo = mmio_read(mmio_base, Config);

    // === Phase 2: Set up virtqueue ===

    // Select queue 0
    mmio_write(mmio_base, QueueSel, 0);

    // Set queue size
    mmio_write(mmio_base, QueueNum, QUEUE_SIZE);

    // Set descriptor table address
    mmio_write(mmio_base, QueueDescLow, qb + OFF_DESC_TABLE);
    mmio_write(mmio_base, QueueDescHigh, 0);

    // Set available ring address
    mmio_write(mmio_base, QueueAvailLow, qb + OFF_AVAIL_RING);
    mmio_write(mmio_base, QueueAvailHigh, 0);

    // Set used ring address
    mmio_write(mmio_base, QueueUsedLow, qb + OFF_USED_RING);
    mmio_write(mmio_base, QueueUsedHigh, 0);

    // Mark queue ready
    mmio_write(mmio_base, QueueReady, 1);

    // === Phase 3: Build read request for sector 0 ===

    // Request header at OFF_REQ_HEADER: type=READ(0), reserved=0, sector=0
    mem_write32(qb + OFF_REQ_HEADER + 0, VIRTIO_BLK_T_IN);  // type = READ
    mem_write32(qb + OFF_REQ_HEADER + 4, 0);                 // reserved
    mem_write32(qb + OFF_REQ_HEADER + 8, 0);                 // sector lo
    mem_write32(qb + OFF_REQ_HEADER + 12, 0);                // sector hi

    // Descriptor 0: request header (16 bytes, read-only, chained)
    let desc0_addr = qb + OFF_DESC_TABLE;
    mem_write32(desc0_addr + 0, qb + OFF_REQ_HEADER);        // addr lo
    mem_write32(desc0_addr + 4, 0);                           // addr hi
    mem_write32(desc0_addr + 8, 16);                          // len
    mem_write32(desc0_addr + 12, (VIRTQ_DESC_F_NEXT as u32) | (1 << 16)); // flags=NEXT, next=1

    // Descriptor 1: data buffer (512 bytes, writable, chained)
    let desc1_addr = qb + OFF_DESC_TABLE + 16;
    mem_write32(desc1_addr + 0, qb + OFF_DATA_BUF);          // addr lo
    mem_write32(desc1_addr + 4, 0);                           // addr hi
    mem_write32(desc1_addr + 8, SECTOR_SIZE as u32);          // len = 512
    mem_write32(desc1_addr + 12, ((VIRTQ_DESC_F_WRITE | VIRTQ_DESC_F_NEXT) as u32) | (2 << 16)); // flags=WRITE|NEXT, next=2

    // Descriptor 2: status byte (1 byte, writable, no chain)
    let desc2_addr = qb + OFF_DESC_TABLE + 32;
    mem_write32(desc2_addr + 0, qb + OFF_STATUS_BYTE);       // addr lo
    mem_write32(desc2_addr + 4, 0);                           // addr hi
    mem_write32(desc2_addr + 8, 1);                           // len = 1
    mem_write32(desc2_addr + 12, VIRTQ_DESC_F_WRITE as u32); // flags=WRITE, next=0

    // Write 0xFF to status byte so we can detect completion
    mem_write32(qb + OFF_STATUS_BYTE, 0xFF);

    // Available ring: set idx=1 and ring[0]=0 (head descriptor index)
    // Layout: flags(2) | idx(2) | ring[0](2) | ...
    // Write as u32: low half=flags=0, high half=idx=1
    mem_write32(qb + OFF_AVAIL_RING, 1 << 16);  // flags=0, idx=1
    mem_write32(qb + OFF_AVAIL_RING + 4, 0);    // ring[0] = 0 (head desc index)

    // === Phase 4: Kick the queue ===
    mmio_write(mmio_base, QueueNotify, 0);

    // === Phase 5: Poll for completion ===
    // The used ring idx should advance to 1 when the request completes
    let mut timeout = 100000u32;
    let mut completed = false;
    while timeout > 0 {
        let used_idx = (mem_read32(qb + OFF_USED_RING) >> 16) as u16;
        if used_idx >= 1 {
            completed = true;
            break;
        }
        timeout -= 1;
    }

    if !completed {
        print_str("BLK: TIMEOUT\n");
        return 0xFFFFFFFD;
    }

    // Read status byte
    let blk_status = unsafe { *(&QUEUE_MEM[OFF_STATUS_BYTE as usize]) };

    // Verify data -- first 4 bytes of sector 0 should be readable
    // (Disk is zeroed, so we just check that the read completed successfully)
    let data_word = mem_read32(qb + OFF_DATA_BUF);

    // === Report ===
    print_str("VirtIO BLK: id=");
    print_hex(dev_id);
    print_str(" sectors=");
    print_hex(capacity_lo);
    print_str(" read_status=");
    print_int(blk_status as i32);
    print_str(" data[0:4]=");
    print_hex(data_word);
    print_str(" ok=");
    print_str(if completed { "1" } else { "0" });
    print_str("\n");

    if blk_status == VIRTIO_BLK_S_OK {
        0  // Success
    } else {
        0xFFFFFFFC  // I/O error
    }
}
