#!/usr/bin/env python3
"""
csv2asm.py -- Compile CSV animation timelines into GeOS assembly.

Input CSV format:
    frame,op,x,y,w,h,r,g,b,text

Supported ops:
    TEXT     -> DRAWTEXT with fg color, optional bg rect
    RECTF    -> RECTF filled rectangle
    FILL     -> FILL entire framebuffer (x/y/w/h ignored)
    LINE     -> LINE from (x,y) to (w,h) with color
    PSET     -> PSET single pixel at (x,y) with color

The 'frame' column controls when each command executes.
Frame 0 commands run immediately. Frame N commands run after N FRAME waits.
Consecutive same-frame commands batch without intermediate FRAME calls.

Usage:
    python3 scripts/csv2asm.py examples/text_commands.csv
    python3 scripts/csv2asm.py examples/text_commands.csv -o programs/output.asm
    python3 scripts/csv2asm.py examples/text_commands.csv --loop
    python3 scripts/csv2asm.py examples/text_commands.csv --bg 0x001020
"""

import csv
import sys
import argparse
import os
import re
from collections import defaultdict


def parse_color(r, g, b):
    """Convert RGB (0-255) to GeOS hex color literal."""
    r = int(r) & 0xFF
    g = int(g) & 0xFF
    b = int(b) & 0xFF
    return f"0x{r:02X}{g:02X}{b:02X}"


def sanitize_label(text):
    """Convert text to a valid asm label."""
    label = re.sub(r'[^A-Za-z0-9_]', '_', text.strip())
    label = re.sub(r'_+', '_', label).strip('_')
    return label[:32] if label else "str"


def compile_csv(rows, bg_color=None, loop=False):
    """
    Compile parsed CSV rows into GeOS assembly source.
    
    rows: list of dicts with keys: frame, op, x, y, w, h, r, g, b, text
    Returns: string of GeOS assembly
    """
    # Group commands by frame
    frames = defaultdict(list)
    for row in rows:
        frames[int(row['frame'])].append(row)
    
    max_frame = max(frames.keys()) if frames else 0
    
    lines = []
    lines.append("; Generated by csv2asm.py from CSV timeline")
    lines.append(f"; {len(rows)} commands across {max_frame + 1} frames")
    if loop:
        lines.append("; Mode: LOOPING animation")
    lines.append("")
    
    # Preamble: select 8x8 font
    lines.append("; === Setup ===")
    lines.append("LDI r0, 1")
    lines.append("FONT_SELECT r0")
    lines.append("LDI r7, 1       ; increment constant")
    lines.append("")
    
    # Background fill if specified
    if bg_color:
        lines.append(f"; Background fill")
        lines.append(f"LDI r0, {bg_color}")
        lines.append("FILL r0")
        lines.append("")
    
    # String storage pool (collected from TEXT ops)
    string_pool = []
    string_labels = {}
    
    def get_string_label(text):
        nonlocal string_pool
        if text in string_labels:
            return string_labels[text]
        # Generate unique label
        base = sanitize_label(text)
        label = f"str_{base}"
        idx = 0
        while label in [s[0] for s in string_pool]:
            idx += 1
            label = f"str_{base}_{idx}"
        string_labels[text] = label
        string_pool.append((label, text))
        return label
    
    # First pass: collect all strings
    for frame_num in sorted(frames.keys()):
        for row in frames[frame_num]:
            if row['op'].upper() == 'TEXT' and row.get('text', '').strip():
                get_string_label(row['text'].strip())
    
    # Animation label if looping
    if loop:
        lines.append("anim_start:")
    
    # Generate frame commands
    current_frame = 0
    for frame_num in sorted(frames.keys()):
        # Insert FRAME waits to reach target frame
        frames_needed = frame_num - current_frame
        if frames_needed > 0:
            lines.append(f"; === Advance to frame {frame_num} ({frames_needed} ticks) ===")
            for _ in range(frames_needed):
                lines.append("FRAME")
            lines.append("")
        current_frame = frame_num
        
        lines.append(f"; === Frame {frame_num} ({len(frames[frame_num])} ops) ===")
        
        for row in frames[frame_num]:
            op = row['op'].upper()
            x = int(row.get('x', 0))
            y = int(row.get('y', 0))
            w = int(row.get('w', 0))
            h = int(row.get('h', 0))
            r = int(row.get('r', 255))
            g = int(row.get('g', 255))
            b = int(row.get('b', 255))
            text = row.get('text', '').strip()
            color = parse_color(r, g, b)
            
            if op == 'FILL':
                lines.append(f"LDI r0, {color}")
                lines.append("FILL r0")
                
            elif op == 'RECTF':
                lines.append(f"LDI r10, {x}")
                lines.append(f"LDI r11, {y}")
                lines.append(f"LDI r12, {w}")
                lines.append(f"LDI r13, {h}")
                lines.append(f"LDI r14, {color}")
                lines.append("RECTF r10, r11, r12, r13, r14")
                
            elif op == 'TEXT':
                if not text:
                    continue
                label = get_string_label(text)
                # Optionally draw background rect first
                if w > 0 and h > 0:
                    lines.append(f"; Background box for \"{text}\"")
                    lines.append(f"LDI r10, {x}")
                    lines.append(f"LDI r11, {y}")
                    lines.append(f"LDI r12, {w}")
                    lines.append(f"LDI r13, {h}")
                    lines.append("LDI r14, 0x000000")
                    lines.append("RECTF r10, r11, r12, r13, r14")
                # Draw text with foreground color
                lines.append(f"LDI r1, {x}")
                lines.append(f"LDI r2, {y}")
                lines.append(f"LDI r3, :{label}")
                lines.append(f"LDI r4, {color}")
                lines.append("LDI r5, 0          ; transparent bg")
                lines.append("DRAWTEXT r1, r2, r3, r4, r5")
                
            elif op == 'LINE':
                lines.append(f"LDI r10, {x}")
                lines.append(f"LDI r11, {y}")
                lines.append(f"LDI r12, {w}")   # w = x2 for LINE
                lines.append(f"LDI r13, {h}")   # h = y2 for LINE
                lines.append(f"LDI r14, {color}")
                lines.append("LINE r10, r11, r12, r13, r14")
                
            elif op == 'PSET':
                lines.append(f"LDI r10, {x}")
                lines.append(f"LDI r11, {y}")
                lines.append(f"LDI r12, {color}")
                lines.append("PSET r10, r11, r12")
                
            elif op == 'CLEAR':
                # Clear with bg color or black
                fill = bg_color if bg_color else "0x000000"
                lines.append(f"LDI r0, {fill}")
                lines.append("FILL r0")
                
            else:
                lines.append(f"; UNKNOWN OP: {op} (skipped)")
        
        lines.append("")
    
    # Loop back if requested
    if loop:
        lines.append("; === Loop back ===")
        if bg_color:
            lines.append(f"LDI r0, {bg_color}")
        else:
            lines.append("LDI r0, 0x000000")
        lines.append("FILL r0")
        # Pause briefly so last frame is visible
        lines.append("FRAME")
        lines.append("JMP anim_start")
    else:
        lines.append("HALT")
    
    lines.append("")
    
    # Emit string pool
    if string_pool:
        lines.append("; === String Pool ===")
        for label, text in string_pool:
            escaped = text.replace('"', '\\"')
            lines.append(f':{label} .str "{escaped}"')
        lines.append("")
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Compile CSV animation timelines into GeOS assembly"
    )
    parser.add_argument("csvfile", help="Path to CSV file")
    parser.add_argument("-o", "--output", help="Output .asm file (default: stdout)")
    parser.add_argument("--bg", help="Background fill color (e.g. 0x001020)")
    parser.add_argument("--loop", action="store_true", help="Loop animation")
    parser.add_argument("--frames-per-tick", type=int, default=1,
                        help="FRAME calls per tick (default: 1)")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.csvfile):
        print(f"Error: {args.csvfile} not found", file=sys.stderr)
        sys.exit(1)
    
    # Parse CSV
    rows = []
    with open(args.csvfile, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Fill missing fields with defaults
            row.setdefault('frame', '0')
            row.setdefault('op', 'TEXT')
            row.setdefault('x', '0')
            row.setdefault('y', '0')
            row.setdefault('w', '0')
            row.setdefault('h', '0')
            row.setdefault('r', '255')
            row.setdefault('g', '255')
            row.setdefault('b', '255')
            row.setdefault('text', '')
            rows.append(row)
    
    if not rows:
        print("Error: CSV file is empty", file=sys.stderr)
        sys.exit(1)
    
    asm = compile_csv(rows, bg_color=args.bg, loop=args.loop)
    
    if args.output:
        with open(args.output, 'w') as f:
            f.write(asm)
        print(f"Wrote {len(rows)} commands -> {args.output}")
    else:
        print(asm)


if __name__ == "__main__":
    main()
