#!/usr/bin/env python3
"""
PixelPack Hex Key v2 Decoder
Turns a hex string into a Geometry OS .asm program.

Usage:
    python3 pixelpack_decoder.py <hex_string> [output.asm]
    python3 pixelpack_decoder.py "D1EB30044EB50044EF"
"""
import sys

# ═══════════════════════════════════════════════════════
# PIXELPACK HEX KEY v2
# ═══════════════════════════════════════════════════════
#
# Even digits = coordinates (spatial)
# Odd digits  = colors (visual)
# Letters A-F = opcodes (actions)

# --- Even digits: coordinates ---
COORDS = {
    '0': 0,     # edge
    '2': 64,    # quarter
    '4': 128,   # center
    '6': 192,   # three-quarter
    '8': 255,   # far edge
}

# --- Odd digits: colors (24-bit RGB) ---
COLORS = {
    '1': 0x000000,  # black
    '3': 0xFF0000,  # red
    '5': 0x00FF00,  # green
    '7': 0x0000FF,  # blue
    '9': 0xFFFFFF,  # white
}

# --- Coercion tables ---
# When a coord slot gets a color digit, map to coord
COLOR_TO_COORD = {
    0x000000: 0,     # black → 0
    0xFF0000: 64,    # red → 64
    0x00FF00: 128,   # green → 128
    0x0000FF: 192,   # blue → 192
    0xFFFFFF: 255,   # white → 255
}

# When a color slot gets a coord digit, map to a brownish palette
COORD_TO_COLOR = {
    0:   0x000000,   # 0 → black
    64:  0x553300,   # dark brown
    128: 0x886622,   # brown
    192: 0xBB9944,   # tan
    255: 0xDDCC88,   # light tan
}

# --- Opcode signatures: (name, param_names, param_types) ---
OPCODES = {
    'A': ('PSET',   ['c', 'x', 'y'],        ['c', 'x', 'y']),
    'B': ('RECTF',  ['c', 'x', 'y', 'w', 'h'], ['c', 'x', 'y', 'x', 'y']),
    'C': ('LINE',   ['c', 'x1', 'y1', 'x2', 'y2'], ['c', 'x', 'y', 'x', 'y']),
    'D': ('FILL',   ['c'],                   ['c']),
    'E': ('FRAME',  [],                      []),
    'F': ('HALT',   [],                      []),
}

# --- Lookup: hex char → native type + value ---
HEX_TABLE = {}
for ch, val in COORDS.items():
    HEX_TABLE[ch] = ('coord', val)
for ch, val in COLORS.items():
    HEX_TABLE[ch] = ('color', val)


def resolve(hex_char: str, expected_type: str) -> int:
    """Resolve a hex character to a value, coercing if type mismatches."""
    ch = hex_char.upper()
    if ch not in HEX_TABLE:
        return 0  # unknown → 0

    native_type, val = HEX_TABLE[ch]

    if native_type == expected_type:
        return val
    elif expected_type == 'coord' and native_type == 'color':
        return COLOR_TO_COORD.get(val, 0)
    elif expected_type == 'color' and native_type == 'coord':
        return COORD_TO_COLOR.get(val, 0)
    else:
        return val


def decode(hex_str: str) -> list:
    """Parse hex string → list of (opcode, {param_name: value}) instructions."""
    hex_str = hex_str.upper().strip()
    i = 0
    instructions = []

    while i < len(hex_str):
        ch = hex_str[i]
        i += 1

        if ch not in OPCODES:
            continue  # skip non-opcode chars at command position

        op_name, param_names, param_types = OPCODES[ch]
        params = {}

        for j, (pname, ptype) in enumerate(zip(param_names, param_types)):
            if i >= len(hex_str):
                break
            pval = resolve(hex_str[i], ptype)
            params[pname] = pval
            i += 1

        instructions.append((op_name, params))

    return instructions


def to_asm(instructions: list, title: str = "PixelPack") -> str:
    """Convert decoded instructions to GeOS assembly."""
    lines = [
        f"; {title}",
        "; Generated by PixelPack v2 decoder",
        "",
    ]

    for op_name, params in instructions:
        if op_name == 'PSET':
            c = params.get('c', 0)
            x = params.get('x', 0)
            y = params.get('y', 0)
            lines.extend([
                f"LDI r20, 0x{c:06X}  ; color",
                f"LDI r21, {x}",
                f"LDI r22, {y}",
                "PSET r21, r22, r20",
                "",
            ])

        elif op_name == 'RECTF':
            c = params.get('c', 0)
            x = params.get('x', 0)
            y = params.get('y', 0)
            w = params.get('w', 0)
            h = params.get('h', 0)
            lines.extend([
                f"LDI r20, 0x{c:06X}  ; color",
                f"LDI r21, {x}",
                f"LDI r22, {y}",
                f"LDI r23, {w}",
                f"LDI r24, {h}",
                "RECTF r21, r22, r23, r24, r20",
                "",
            ])

        elif op_name == 'LINE':
            c = params.get('c', 0)
            x1 = params.get('x1', 0)
            y1 = params.get('y1', 0)
            x2 = params.get('x2', 0)
            y2 = params.get('y2', 0)
            lines.extend([
                f"LDI r20, 0x{c:06X}",
                f"LDI r21, {x1}",
                f"LDI r22, {y1}",
                f"LDI r23, {x2}",
                f"LDI r24, {y2}",
                "LINE r21, r22, r23, r24, r20",
                "",
            ])

        elif op_name == 'FILL':
            c = params.get('c', 0)
            lines.extend([
                f"LDI r20, 0x{c:06X}",
                "FILL r20",
                "",
            ])

        elif op_name == 'FRAME':
            lines.append("FRAME")
            lines.append("")

        elif op_name == 'HALT':
            lines.append("HALT")

    if not lines or not any(l.strip().startswith('HALT') for l in lines):
        lines.append("HALT")

    return '\n'.join(lines)


def explain(hex_str: str) -> str:
    """Human-readable explanation of a hex string."""
    hex_str = hex_str.upper().strip()
    instructions = decode(hex_str)
    parts = []

    # Also show the raw char breakdown
    raw = []
    i = 0
    while i < len(hex_str):
        ch = hex_str[i]
        if ch in OPCODES:
            op_name, param_names, param_types = OPCODES[ch]
            raw.append(f"{ch}={op_name}")
            i += 1
            for ptype in param_types:
                if i < len(hex_str):
                    pch = hex_str[i]
                    if pch in COORDS:
                        raw.append(f"{pch}({COORDS[pch]})")
                    elif pch in COLORS:
                        cname = {0x000000:'blk', 0xFF0000:'red', 0x00FF00:'grn',
                                 0x0000FF:'blu', 0xFFFFFF:'wht'}[COLORS[pch]]
                        raw.append(f"{pch}({cname})")
                    else:
                        raw.append(f"{pch}(?)")
                    i += 1
        else:
            if ch in COORDS:
                raw.append(f"{ch}({COORDS[ch]})")
            elif ch in COLORS:
                raw.append(f"{ch}(color)")
            else:
                raw.append(f"{ch}(?)")
            i += 1

    parts.append("Chars: " + " ".join(raw))
    parts.append("")

    for op_name, params in instructions:
        pstr = ", ".join(f"{k}={v}" for k, v in params.items())
        parts.append(f"  {op_name}({pstr})")

    return '\n'.join(parts)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        print("\nExamples:")
        print('  python3 pixelpack_decoder.py "D1EB30044EF"')
        print('  python3 pixelpack_decoder.py "B30044EB50044EF" out.asm')
        sys.exit(1)

    hex_str = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None

    print(f"=== PixelPack v2 Decoder ===")
    print(f"Input: {hex_str} ({len(hex_str)} chars)")
    print()

    print(explain(hex_str))
    print()

    instructions = decode(hex_str)
    asm = to_asm(instructions, f"PixelPack: {hex_str}")

    if output_file:
        with open(output_file, 'w') as f:
            f.write(asm)
        print(f"Saved to: {output_file}")
    else:
        print("Generated ASM:")
        print(asm)
