"""
Bridge: Pixel LLM -> Geometry OS substrate.

Takes generated assembly text, assembles it into pixel values,
and produces output loadable by the Rust substrate.

This is the link between the neural network and the GPU VM.
"""

import struct
import sys
from model import decode, TOKEN_TO_ID, ID_TO_TOKEN, OPCODES, REGS

# Opcode name -> byte value (matching src/assembler.rs op module)
OPCODE_MAP = {
    'NOP': 0, 'LDI': 1, 'MOV': 2, 'LOAD': 3, 'STORE': 4,
    'ADD': 5, 'SUB': 6, 'MUL': 7, 'DIV': 8, 'JMP': 9,
    'BNE': 10, 'CALL': 11, 'RET': 12, 'HALT': 13,
    'DRAW': 215, 'SPAWN': 230,
}


def encode_glyph(opcode: int, stratum: int, p1: int, p2: int) -> int:
    """Encode a 32-bit glyph instruction (same as assembler.rs glyph())."""
    return (opcode & 0xFF) | ((stratum & 0xFF) << 8) | ((p1 & 0xFF) << 16) | ((p2 & 0xFF) << 24)


def assemble_line(line: str) -> list[int]:
    """
    Assemble a single line of text into pixel values.
    Returns list of u32 values (1-2 pixels depending on instruction).
    """
    parts = line.strip().split()
    if not parts:
        return []

    op_name = parts[0].upper()

    if op_name not in OPCODE_MAP:
        return []

    opcode = OPCODE_MAP[op_name]

    if op_name == 'NOP':
        return [encode_glyph(0, 0, 0, 0)]

    elif op_name == 'LDI':
        # LDI reg, value -> [glyph] [data word]
        if len(parts) < 3:
            return []
        try:
            reg = int(parts[1][1])  # r0-r7
            value = int(parts[2]) & 0xFF  # clamp to 0-255
        except (IndexError, ValueError):
            return []
        return [encode_glyph(opcode, 0, reg, 0), value]

    elif op_name == 'MOV':
        try:
            dst = int(parts[1][1])
            src = int(parts[2][1])
        except (IndexError, ValueError):
            return []
        return [encode_glyph(opcode, 0, dst, src)]

    elif op_name in ('LOAD', 'STORE'):
        # LOAD dst, [addr_reg] or STORE [addr_reg], src
        try:
            p1 = int(parts[1][1])
            p2 = int(parts[2][1])
        except (IndexError, ValueError):
            return []  # Invalid register reference
        return [encode_glyph(opcode, 0, p1, p2)]

    elif op_name in ('ADD', 'SUB', 'MUL', 'DIV'):
        try:
            dst = int(parts[1][1])
            src = int(parts[2][1])
        except (IndexError, ValueError):
            return []
        return [encode_glyph(opcode, 0, dst, src)]

    elif op_name == 'BNE':
        try:
            r1 = int(parts[1][1])
            r2 = int(parts[2][1])
            offset = int(parts[3])
        except (IndexError, ValueError):
            return []
        # BNE is opcode 10, stratum=1 (BNE condition)
        return [encode_glyph(10, 1, r1, r2), offset & 0xFFFFFFFF]

    elif op_name == 'CALL':
        addr = int(parts[1]) & 0xFF
        return [encode_glyph(opcode, 0, addr, 0)]

    elif op_name == 'RET':
        return [encode_glyph(opcode, 0, 0, 0)]

    elif op_name == 'HALT':
        return [encode_glyph(opcode, 0, 0, 0)]

    elif op_name == 'JMP':
        offset = int(parts[1]) & 0xFFFFFFFF
        return [encode_glyph(opcode, 0, 0, 0), offset]

    return []


def assemble_program(text: str) -> list[int]:
    """
    Assemble a full program from text to pixel values.
    Returns list of u32 values ready to load into the substrate.
    """
    pixels = []
    for line in text.strip().split('\n'):
        line = line.strip()
        if not line or line.startswith('//'):
            continue
        px = assemble_line(line)
        pixels.extend(px)
    return pixels


def pixels_to_bytes(pixels: list[int]) -> bytes:
    """Convert pixel list to raw bytes for substrate loading."""
    return b''.join(struct.pack('<I', p) for p in pixels)


def pixels_to_hex(pixels: list[int]) -> str:
    """Convert pixel list to hex string."""
    return ' '.join(f'0x{p:08X}' for p in pixels)


def write_load_script(pixels: list[int], start_addr: int, path: str):
    """
    Write a Rust test file that loads the given pixels into the substrate
    and runs them on GPU. This is the bridge from Python -> Rust.
    """
    pixel_literals = ', '.join(f'0x{p:08X}' for p in pixels)
    template = f'''// Auto-generated by pixel-llm bridge
// {len(pixels)} pixels at address {start_addr}

use pixels_move_pixels::vm::GlyphVm;

#[test]
fn llm_generated_program() {{
    let mut vm = GlyphVm::new();

    // Load LLM-generated program
    let pixels: Vec<u32> = vec![{pixel_literals}];
    vm.substrate().load_program({start_addr}, &pixels);
    vm.spawn_vm(0, {start_addr});
    vm.execute_frame();

    // Program ran successfully if we get here without panic
    println!("LLM program executed: {{}} pixels, {{}} instructions",
        {len(pixels)},
        {len(pixels)} / 2,  // rough estimate
    );
}}
'''
    with open(path, 'w') as f:
        f.write(template)
    print(f"Wrote test to {path}")


if __name__ == '__main__':
    # Demo: assemble a self-replicator and show pixels
    prog = """LDI r0 0
LDI r1 100
LDI r2 0
LDI r3 1
LDI r4 18
LOAD r5 r0
STORE r1 r5
ADD r0 r3
ADD r1 r3
ADD r2 r3
BNE r2 r4 -7
HALT"""

    pixels = assemble_program(prog)
    print(f"Assembled: {len(pixels)} pixels")
    print(f"Hex: {pixels_to_hex(pixels)}")
    print(f"Bytes: {len(pixels_to_bytes(pixels))} bytes")
