// Diagnostic: read the allocation failure details
use std::fs;

fn main() {
    let kernel_path = ".geometry_os/build/linux-6.14/vmlinux";
    let initramfs_path = ".geometry_os/fs/linux/rv32/initramfs.cpio.gz";
    let kernel_image = fs::read(kernel_path).expect("kernel");
    let initramfs = fs::read(initramfs_path).ok();

    let bootargs = "console=ttyS0 earlycon=sbi panic=5 quiet";
    let (mut vm, _result) = geometry_os::riscv::RiscvVm::boot_linux(
        &kernel_image,
        initramfs.as_deref(),
        512,
        20_000_000u64,
        bootargs,
    )
    .unwrap();

    // Read the %s argument: a1=0xC0C1B830 (function name)
    // This is a VA in .rodata. Read the string.
    let name_va = 0xC0C1B830u64;
    let name_pa = name_va - 0xC0000000;
    let mut chars = Vec::new();
    for j in 0..100 {
        let b = vm.bus.read_byte(name_pa + j as u64).unwrap_or(0);
        if b == 0 {
            break;
        }
        if b >= 0x20 && b < 0x7f {
            chars.push(b as char);
        } else {
            break;
        }
    }
    let name: String = chars.iter().collect();
    println!("Caller function name: \"{}\"", name);

    // Read the allocation size: a2=0xC1401E9C
    // This is a pointer to a struct, likely memblock_region or similar
    let size_ptr_va = 0xC1401E9Cu64;
    let size_ptr_pa = size_ptr_va - 0xC0000000;
    let size_val = vm.bus.read_word(size_ptr_pa).unwrap_or(0);
    println!(
        "Size value at VA 0x{:08X}: 0x{:08X} ({} bytes)",
        size_ptr_va, size_val, size_val
    );

    // The allocation address was t0=0x9DC00000 -- this is suspiciously high
    // It's in the VMALLOC area, not regular RAM
    println!("\nAllocation address (t0): 0x9DC00000");
    println!("This is NOT in kernel linear mapping (0xC0000000+) or physical RAM range");

    // Check memblock state -- look for the memblock array in .data/.bss
    // The memblock regions array should be at a known address
    // Let's check if there's a memblock bottom/top set incorrectly

    // The real issue: the kernel thinks physical RAM ends at a certain address
    // but our megapage injection doesn't cover enough memory, or the
    // DTB memory node specifies the wrong size

    // Check the DTB memory node
    // The DTB is loaded at a known address -- let's find it
    // From boot.rs, the DTB address is calculated from initrd_end
    // Let's check what memory size the DTB advertises
    println!("\n--- Checking DTB memory node ---");

    // Search for the DTB magic (0xd00dfeed)
    let mut dtb_found = false;
    for addr in (0x01400000..0x01600000).step_by(4) {
        let w = vm.bus.read_word(addr).unwrap_or(0);
        if w == 0xd00dfeed {
            println!("DTB found at PA 0x{:08X}", addr);
            dtb_found = true;
            // Parse FDT header to find memory reservation map and memory node
            // For now, just print some context
            break;
        }
    }

    // The DTB was generated by our dtb.rs module. Let's check what ram_size it uses.
    // The default is 512MB. But the kernel only has ~22MB of actual code/data.
    // The memblock allocator should work fine with 512MB.

    // Wait -- the allocation address 0x9DC00000 looks wrong.
    // Let me check if this is a PHYSICAL address or virtual address.
    // In __memblock_alloc, the returned address is a physical address.
    // 0x9DC00000 = ~2.5GB -- that's above 512MB RAM!
    // This means the memblock thinks RAM extends to 2.5GB+

    // Actually, let me re-read the panic format: "%s: Failed to allocate %pap bytes"
    // %pap prints a phys_addr_t. The allocation SIZE is what's being printed.
    // Let me re-check the args:
    // a0 = fmt string ptr
    // a1 = first %s arg = function name ptr (0xC0C1B830)
    // For %pap, the next arg is a phys_addr_t (possibly 64-bit on 32-bit, passed as two 32-bit args)
    // a2 might be the low 32 bits of the phys_addr_t
    // But wait, the format says "Failed to allocate %pap bytes" -- %pap is the SIZE being allocated

    // Actually looking more carefully, %pap prints a physical address value
    // The function is __memblock_alloc_or_panic, and the format shows it failed to allocate
    // Let me check what the actual allocation request was

    // The key insight: RA=0xC040DD14 is inside __memblock_alloc_or_panic
    // The kernel can't allocate memory from the memblock pool
    // This likely means the memblock doesn't have any memory regions registered
    // or the memory regions are too small

    // The DTB should define the memory node. Let's check what memory our DTB provides.
    // The issue might be that our megapage injection or identity mapping is
    // interfering with the kernel's memory discovery.
}
