; Generated by pixelc

main:
LDI r0, 10
LDI r1, 10
LDI r2, 3
LDI r3, 2
LDI r4, 0
while_1:
MOV r28, r4
LDI r29, 200
BGE r28, r29, endw_2
MOV r28, r0
MOV r29, r1
LDI r30, 0
PSET r28, r29, r30
MOV r28, r0
MOV r29, r2
ADD r28, r29
MOV r0, r28
MOV r28, r1
MOV r29, r3
ADD r28, r29
MOV r1, r28
MOV r28, r0
LDI r29, 200
BLT r28, r29, else_3
LDI r28, 0
MOV r29, r2
SUB r28, r29
MOV r2, r28
MOV r28, r0
MOV r29, r2
ADD r28, r29
MOV r0, r28
else_3:
MOV r28, r1
LDI r29, 200
BLT r28, r29, else_5
LDI r28, 0
MOV r29, r3
SUB r28, r29
MOV r3, r28
MOV r28, r1
MOV r29, r3
ADD r28, r29
MOV r1, r28
else_5:
MOV r28, r0
LDI r29, 3
BGE r28, r29, else_7
LDI r28, 0
MOV r29, r2
SUB r28, r29
MOV r2, r28
MOV r28, r0
MOV r29, r2
ADD r28, r29
MOV r0, r28
else_7:
MOV r28, r1
LDI r29, 3
BGE r28, r29, else_9
LDI r28, 0
MOV r29, r3
SUB r28, r29
MOV r3, r28
MOV r28, r1
MOV r29, r3
ADD r28, r29
MOV r1, r28
else_9:
MOV r28, r0
MOV r29, r1
LDI r30, 65
PSET r28, r29, r30
MOV r28, r4
LDI r29, 1
ADD r28, r29
MOV r4, r28
JMP while_1
endw_2:
HALT
HALT
