; Generated by pixelc

main:
LDI r0, 0
while_1:
MOV r28, r0
LDI r29, 64
BGE r28, r29, endw_2
LDI r1, 0
while_3:
MOV r28, r1
LDI r29, 64
BGE r28, r29, endw_4
MOV r28, r1
MOV r29, r0
ADD r28, r29
MOV r2, r28
MOV r28, r2
LDI r29, 2
MOD r28, r29
MOV r3, r28
MOV r28, r3
LDI r29, 0
BNE r28, r29, else_5
MOV r28, r1
MOV r29, r0
LDI r30, 65
PSET r28, r29, r30
JMP endif_6
else_5:
MOV r28, r1
MOV r29, r0
LDI r30, 32
PSET r28, r29, r30
endif_6:
MOV r28, r1
LDI r29, 1
ADD r28, r29
MOV r1, r28
JMP while_3
endw_4:
MOV r28, r0
LDI r29, 1
ADD r28, r29
MOV r0, r28
JMP while_1
endw_2:
HALT
HALT
