; Generated by csv2asm.py from CSV timeline
; 3 commands across 3 frames

; === Setup ===
LDI r0, 1
FONT_SELECT r0
LDI r7, 1       ; increment constant

; Background fill
LDI r0, 0x000033
FILL r0

; === Frame 0 (1 ops) ===
; Background box for "HELLO WORLD"
LDI r10, 110
LDI r11, 250
LDI r12, 300
LDI r13, 20
LDI r14, 0x000000
RECTF r10, r11, r12, r13, r14
LDI r1, 110
LDI r2, 250
LDI r3, :str_HELLO_WORLD
LDI r4, 0xFFFFFF
LDI r5, 0          ; transparent bg
DRAWTEXT r1, r2, r3, r4, r5

; === Advance to frame 1 (1 ticks) ===
FRAME

; === Frame 1 (1 ops) ===
; Background box for "FRAME 2"
LDI r10, 140
LDI r11, 250
LDI r12, 300
LDI r13, 20
LDI r14, 0x000000
RECTF r10, r11, r12, r13, r14
LDI r1, 140
LDI r2, 250
LDI r3, :str_FRAME_2
LDI r4, 0xFFC800
LDI r5, 0          ; transparent bg
DRAWTEXT r1, r2, r3, r4, r5

; === Advance to frame 2 (1 ticks) ===
FRAME

; === Frame 2 (1 ops) ===
; Background box for "FRAME 3"
LDI r10, 170
LDI r11, 250
LDI r12, 300
LDI r13, 20
LDI r14, 0x000000
RECTF r10, r11, r12, r13, r14
LDI r1, 170
LDI r2, 250
LDI r3, :str_FRAME_3
LDI r4, 0xFF9600
LDI r5, 0          ; transparent bg
DRAWTEXT r1, r2, r3, r4, r5

HALT

; === String Pool ===
:str_HELLO_WORLD .str "HELLO WORLD"
:str_FRAME_2 .str "FRAME 2"
:str_FRAME_3 .str "FRAME 3"
