; Generated by csv2asm.py from CSV timeline
; 15 commands across 5 frames
; Mode: LOOPING animation

; === Setup ===
LDI r0, 1
FONT_SELECT r0
LDI r7, 1       ; increment constant

anim_start:
; === Frame 0 (3 ops) ===
LDI r0, 0x001020
FILL r0
; Background box for "GEOMETRY OS"
LDI r10, 60
LDI r11, 20
LDI r12, 200
LDI r13, 16
LDI r14, 0x000000
RECTF r10, r11, r12, r13, r14
LDI r1, 60
LDI r2, 20
LDI r3, :str_GEOMETRY_OS
LDI r4, 0xFFFFFF
LDI r5, 0          ; transparent bg
DRAWTEXT r1, r2, r3, r4, r5
; Background box for "csv2asm timeline demo"
LDI r10, 40
LDI r11, 50
LDI r12, 200
LDI r13, 16
LDI r14, 0x000000
RECTF r10, r11, r12, r13, r14
LDI r1, 40
LDI r2, 50
LDI r3, :str_csv2asm_timeline_demo
LDI r4, 0x64C8FF
LDI r5, 0          ; transparent bg
DRAWTEXT r1, r2, r3, r4, r5

; === Advance to frame 1 (1 ticks) ===
FRAME

; === Frame 1 (4 ops) ===
LDI r10, 20
LDI r11, 80
LDI r12, 100
LDI r13, 30
LDI r14, 0xFF4444
RECTF r10, r11, r12, r13, r14
LDI r10, 130
LDI r11, 80
LDI r12, 100
LDI r13, 30
LDI r14, 0x44FF44
RECTF r10, r11, r12, r13, r14
LDI r10, 20
LDI r11, 120
LDI r12, 100
LDI r13, 30
LDI r14, 0x4488FF
RECTF r10, r11, r12, r13, r14
LDI r10, 130
LDI r11, 120
LDI r12, 100
LDI r13, 30
LDI r14, 0xFFDD00
RECTF r10, r11, r12, r13, r14

; === Advance to frame 2 (1 ticks) ===
FRAME

; === Frame 2 (4 ops) ===
; Background box for "RED"
LDI r10, 35
LDI r11, 87
LDI r12, 80
LDI r13, 16
LDI r14, 0x000000
RECTF r10, r11, r12, r13, r14
LDI r1, 35
LDI r2, 87
LDI r3, :str_RED
LDI r4, 0xFFFFFF
LDI r5, 0          ; transparent bg
DRAWTEXT r1, r2, r3, r4, r5
; Background box for "GREEN"
LDI r10, 145
LDI r11, 87
LDI r12, 80
LDI r13, 16
LDI r14, 0x000000
RECTF r10, r11, r12, r13, r14
LDI r1, 145
LDI r2, 87
LDI r3, :str_GREEN
LDI r4, 0xFFFFFF
LDI r5, 0          ; transparent bg
DRAWTEXT r1, r2, r3, r4, r5
; Background box for "BLUE"
LDI r10, 35
LDI r11, 127
LDI r12, 80
LDI r13, 16
LDI r14, 0x000000
RECTF r10, r11, r12, r13, r14
LDI r1, 35
LDI r2, 127
LDI r3, :str_BLUE
LDI r4, 0xFFFFFF
LDI r5, 0          ; transparent bg
DRAWTEXT r1, r2, r3, r4, r5
; Background box for "GOLD"
LDI r10, 140
LDI r11, 127
LDI r12, 80
LDI r13, 16
LDI r14, 0x000000
RECTF r10, r11, r12, r13, r14
LDI r1, 140
LDI r2, 127
LDI r3, :str_GOLD
LDI r4, 0xFFFFFF
LDI r5, 0          ; transparent bg
DRAWTEXT r1, r2, r3, r4, r5

; === Advance to frame 3 (1 ticks) ===
FRAME

; === Frame 3 (2 ops) ===
LDI r0, 0x001020
FILL r0
; Background box for "CSV POWERED GEOS"
LDI r10, 30
LDI r11, 100
LDI r12, 250
LDI r13, 20
LDI r14, 0x000000
RECTF r10, r11, r12, r13, r14
LDI r1, 30
LDI r2, 100
LDI r3, :str_CSV_POWERED_GEOS
LDI r4, 0xFFC864
LDI r5, 0          ; transparent bg
DRAWTEXT r1, r2, r3, r4, r5

; === Advance to frame 4 (1 ticks) ===
FRAME

; === Frame 4 (2 ops) ===
LDI r10, 30
LDI r11, 125
LDI r12, 226
LDI r13, 125
LDI r14, 0xFF6464
LINE r10, r11, r12, r13, r14
; Background box for "frame-by-frame control"
LDI r10, 30
LDI r11, 135
LDI r12, 250
LDI r13, 16
LDI r14, 0x000000
RECTF r10, r11, r12, r13, r14
LDI r1, 30
LDI r2, 135
LDI r3, :str_frame_by_frame_control
LDI r4, 0xC8C8C8
LDI r5, 0          ; transparent bg
DRAWTEXT r1, r2, r3, r4, r5

; === Loop back ===
LDI r0, 0x000000
FILL r0
FRAME
JMP anim_start

; === String Pool ===
:str_GEOMETRY_OS .str "GEOMETRY OS"
:str_csv2asm_timeline_demo .str "csv2asm timeline demo"
:str_RED .str "RED"
:str_GREEN .str "GREEN"
:str_BLUE .str "BLUE"
:str_GOLD .str "GOLD"
:str_CSV_POWERED_GEOS .str "CSV POWERED GEOS"
:str_frame_by_frame_control .str "frame-by-frame control"
