; Generated by pixelc

main:
LDI r0, 0
while_1:
MOV r28, r0
LDI r29, 100
BGE r28, r29, endw_2
MOV r28, r0
MOV r29, r0
LDI r30, 65
PSET r28, r29, r30
MOV r28, r0
LDI r29, 1
ADD r28, r29
MOV r0, r28
JMP while_1
endw_2:
HALT
HALT
