; Generated by pixelc

main:
LDI r0, 1
LDI r1, 1
LDI r2, 0
while_1:
MOV r28, r2
LDI r29, 20
BGE r28, r29, endw_2
MOV r28, r0
MOV r29, r2
LDI r30, 65
PSET r28, r29, r30
MOV r28, r0
MOV r29, r1
ADD r28, r29
MOV r3, r28
MOV r0, r1
MOV r1, r3
MOV r28, r2
LDI r29, 1
ADD r28, r29
MOV r2, r28
JMP while_1
endw_2:
HALT
HALT
