; Generated by pixelc

main:
LDI r0, 0
while_1:
MOV r28, r0
PUSH r28
LDI r28, 64
POP r29
BGE r29, r28, endw_2
LDI r1, 0
while_3:
MOV r28, r1
PUSH r28
LDI r28, 64
POP r29
BGE r29, r28, endw_4
MOV r2, r0
PUSH r2
LDI r2, 4
PUSH r2
POP r28
POP r29
MUL r29, r28
MOV r2, r29
MOV r3, r2
PUSH r3
MOV r3, r1
PUSH r3
POP r28
POP r29
ADD r29, r28
MOV r3, r29
MOV r28, r1
PUSH r28
MOV r28, r0
PUSH r28
MOV r28, r3
PUSH r28
POP r28
POP r29
POP r30
PSET r28, r29, r30
PUSH r1
LDI r1, 1
PUSH r1
POP r28
POP r29
ADD r29, r28
MOV r1, r29
JMP while_3
endw_4:
PUSH r0
LDI r0, 1
PUSH r0
POP r28
POP r29
ADD r29, r28
MOV r0, r29
JMP while_1
endw_2:
HALT
HALT
