"""
Meta-Prompter Evolution Hook

Uses the results of auto-prompting as a fitness signal to evolve PixelBrain
for better task-planning capabilities.

Integration Points:
1. PostToolUse: Reward when tool succeeds after meta-prompt
2. PostToolUseFailure: Punish when tool fails after meta-prompt
3. Stop: Track prompt outcomes for batch fitness evaluation

This creates a feedback loop where the brain learns which prompts
lead to successful outcomes in Geometry OS context.
"""

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Track active prompts and their outcomes
PROMPT_TRACKING_FILE = Path("/home/jericho/zion/projects/geometry_os/geometry_os/.geometry/meta_prompter_tracking.json")


@dataclass
class PromptOutcome:
    """Record of a meta-prompt and its outcome."""
    timestamp: str
    prompt: str
    source_event: str  # Stop, Notification, etc.
    tool_calls: list[str] = field(default_factory=list)
    successes: int = 0
    failures: int = 0
    final_status: str = "pending"  # pending, success, failure, timeout


class MetaPrompterEvolutionHook:
    """
    Hook for evolving PixelBrain based on meta-prompter outcomes.

    This hook tracks prompts generated by the meta-prompter and uses
    their outcomes as fitness signals for brain evolution.

    Usage:
        hook = MetaPrompterEvolutionHook()
        daemon.register_hook('PostToolUse', hook.on_tool_success)
        daemon.register_hook('PostToolUseFailure', hook.on_tool_failure)
        daemon.register_hook('evolution_cycle', hook.on_evolution_cycle)
    """

    def __init__(
        self,
        brain_path: str = "tinystories_brain.rts.png",
        reward_weight: float = 0.1,
        punish_weight: float = 0.05,
        batch_size: int = 10
    ):
        """Initialize the meta-prompter evolution hook.

        Args:
            brain_path: Path to the brain atlas file
            reward_weight: How much to strengthen weights on success
            punish_weight: How much to weaken weights on failure
            batch_size: Number of outcomes before triggering evolution
        """
        self.brain_path = brain_path
        self.reward_weight = reward_weight
        self.punish_weight = punish_weight
        self.batch_size = batch_size

        self.pending_outcomes: list[PromptOutcome] = []
        self.completed_outcomes: list[PromptOutcome] = []
        self.current_prompt: PromptOutcome | None = None

        self._load_tracking()

    def _load_tracking(self):
        """Load prompt tracking from disk."""
        try:
            if PROMPT_TRACKING_FILE.exists():
                with open(PROMPT_TRACKING_FILE) as f:
                    data = json.load(f)
                    self.completed_outcomes = [
                        PromptOutcome(**o) for o in data.get("completed", [])
                    ]
                    logger.info(f"Loaded {len(self.completed_outcomes)} tracked outcomes")
        except Exception as e:
            logger.warning(f"Could not load tracking: {e}")

    def _save_tracking(self):
        """Save prompt tracking to disk."""
        try:
            PROMPT_TRACKING_FILE.parent.mkdir(parents=True, exist_ok=True)
            data = {
                "completed": [
                    {
                        "timestamp": o.timestamp,
                        "prompt": o.prompt,
                        "source_event": o.source_event,
                        "tool_calls": o.tool_calls,
                        "successes": o.successes,
                        "failures": o.failures,
                        "final_status": o.final_status
                    }
                    for o in self.completed_outcomes[-100:]  # Keep last 100
                ]
            }
            with open(PROMPT_TRACKING_FILE, "w") as f:
                json.dump(data, f, indent=2)
        except Exception as e:
            logger.warning(f"Could not save tracking: {e}")

    def on_meta_prompt_generated(self, prompt: str, source_event: str) -> None:
        """Called when meta-prompter generates a prompt.

        This starts tracking a new prompt outcome.
        """
        self.current_prompt = PromptOutcome(
            timestamp=datetime.utcnow().isoformat(),
            prompt=prompt,
            source_event=source_event
        )
        logger.info(f"Tracking new meta-prompt: {prompt[:50]}...")

    async def on_tool_success(self, tool_data: dict[str, Any]) -> dict[str, Any]:
        """Called after a successful tool execution.

        If this tool was triggered by a meta-prompt, record success.
        """
        if self.current_prompt is None:
            return {"tracked": False, "reason": "no active prompt"}

        tool_name = tool_data.get("tool_name", "unknown")
        self.current_prompt.tool_calls.append(tool_name)
        self.current_prompt.successes += 1

        logger.info(f"Meta-prompt tool success: {tool_name}")

        return {
            "tracked": True,
            "prompt": self.current_prompt.prompt[:50],
            "tool": tool_name,
            "successes": self.current_prompt.successes
        }

    async def on_tool_failure(self, tool_data: dict[str, Any]) -> dict[str, Any]:
        """Called after a failed tool execution.

        If this tool was triggered by a meta-prompt, record failure.
        """
        if self.current_prompt is None:
            return {"tracked": False, "reason": "no active prompt"}

        tool_name = tool_data.get("tool_name", "unknown")
        self.current_prompt.tool_calls.append(tool_name)
        self.current_prompt.failures += 1

        logger.info(f"Meta-prompt tool failure: {tool_name}")

        return {
            "tracked": True,
            "prompt": self.current_prompt.prompt[:50],
            "tool": tool_name,
            "failures": self.current_prompt.failures
        }

    async def on_turn_complete(self, turn_data: dict[str, Any]) -> dict[str, Any]:
        """Called when a turn completes (Stop event).

        Finalize the current prompt outcome and potentially trigger evolution.
        """
        if self.current_prompt is None:
            return {"tracked": False, "reason": "no active prompt"}

        # Determine final status
        if self.current_prompt.successes > self.current_prompt.failures:
            self.current_prompt.final_status = "success"
        elif self.current_prompt.failures > 0:
            self.current_prompt.final_status = "failure"
        else:
            self.current_prompt.final_status = "neutral"

        # Move to completed
        self.completed_outcomes.append(self.current_prompt)
        self._save_tracking()

        result = {
            "tracked": True,
            "prompt": self.current_prompt.prompt[:50],
            "final_status": self.current_prompt.final_status,
            "successes": self.current_prompt.successes,
            "failures": self.current_prompt.failures,
            "total_outcomes": len(self.completed_outcomes)
        }

        # Check if we should trigger evolution
        if len(self.completed_outcomes) >= self.batch_size:
            evolution_result = await self._trigger_evolution()
            result["evolution"] = evolution_result

        self.current_prompt = None
        return result

    async def _trigger_evolution(self) -> dict[str, Any]:
        """Trigger brain evolution based on accumulated outcomes."""
        try:
            from systems.visual_shell.api.pixel_brain_service import get_pixel_brain_service

            # Calculate fitness signal from outcomes
            recent = self.completed_outcomes[-self.batch_size:]
            success_rate = sum(1 for o in recent if o.final_status == "success") / len(recent)

            logger.info(f"Meta-prompter success rate: {success_rate:.2%}")

            # Get the brain service
            service = get_pixel_brain_service()
            if not service or not service.is_available():
                return {"evolved": False, "reason": "PixelBrain not available"}

            # Determine mutation based on success rate
            if success_rate > 0.7:
                # High success: small reinforcement mutation
                mutation_rate = self.reward_weight
                mutation_type = "gaussian"
                sector = "attention_layer_0"  # Focus on attention for better context
            elif success_rate < 0.3:
                # Low success: larger exploratory mutation
                mutation_rate = self.punish_weight * 2
                mutation_type = "uniform"
                sector = "ffn_layer_0"  # Explore FFN for different patterns
            else:
                # Mixed results: moderate exploration
                mutation_rate = self.reward_weight / 2
                mutation_type = "gaussian"
                sector = "attention_layer_1"

            # Apply mutation
            result = {
                "evolved": True,
                "success_rate": success_rate,
                "mutation_rate": mutation_rate,
                "mutation_type": mutation_type,
                "sector": sector,
                "outcomes_analyzed": len(recent)
            }

            logger.info(
                f"Triggering brain evolution: rate={success_rate:.2%}, "
                f"mutation={mutation_type}@{mutation_rate}, sector={sector}"
            )

            # Note: Actual mutation would be applied by BrainEvolutionHook
            # This hook just provides the fitness signal
            return result

        except Exception as e:
            logger.error(f"Evolution trigger failed: {e}")
            return {"evolved": False, "error": str(e)}

    async def on_evolution_cycle(self, cycle_data: dict[str, Any]) -> dict[str, Any]:
        """Called during evolution cycles to apply meta-prompter fitness.

        This integrates with the main BrainEvolutionHook by providing
        fitness signals specific to meta-prompting tasks.
        """
        # Check if we have enough data
        if len(self.completed_outcomes) < 5:
            return {"skipped": True, "reason": "insufficient outcome data"}

        # Calculate meta-prompter specific fitness
        recent = self.completed_outcomes[-20:]
        success_rate = sum(1 for o in recent if o.final_status == "success") / len(recent)

        # Calculate average tool success per prompt
        avg_successes = sum(o.successes for o in recent) / len(recent)
        avg_failures = sum(o.failures for o in recent) / len(recent)

        # Fitness is combination of success rate and efficiency
        fitness = success_rate * 0.7 + (avg_successes / (avg_successes + avg_failures + 0.1)) * 0.3

        return {
            "meta_prompter_fitness": fitness,
            "success_rate": success_rate,
            "avg_successes_per_prompt": avg_successes,
            "avg_failures_per_prompt": avg_failures,
            "total_prompts_tracked": len(self.completed_outcomes),
            "recent_samples": len(recent)
        }

    def get_stats(self) -> dict[str, Any]:
        """Get statistics about meta-prompter performance."""
        if not self.completed_outcomes:
            return {"total": 0}

        recent = self.completed_outcomes[-50:]
        success_count = sum(1 for o in recent if o.final_status == "success")
        failure_count = sum(1 for o in recent if o.final_status == "failure")

        total_tools = sum(len(o.tool_calls) for o in recent)
        total_successes = sum(o.successes for o in recent)
        total_failures = sum(o.failures for o in recent)

        return {
            "total_prompts": len(self.completed_outcomes),
            "recent_prompts": len(recent),
            "success_rate": success_count / len(recent) if recent else 0,
            "failure_rate": failure_count / len(recent) if recent else 0,
            "total_tool_calls": total_tools,
            "tool_success_rate": total_successes / (total_successes + total_failures) if (total_successes + total_failures) > 0 else 0,
            "current_prompt": self.current_prompt.prompt[:50] if self.current_prompt else None
        }


# Integration with Claude Code hooks
def create_claude_hook_integration():
    """Create integration functions for Claude Code hooks.

    These can be called from the meta-prompter hook script.
    """
    hook = MetaPrompterEvolutionHook()

    async def on_prompt_generated(prompt: str, event: str):
        hook.on_meta_prompt_generated(prompt, event)

    async def on_post_tool_use(tool_data: dict):
        return await hook.on_tool_success(tool_data)

    async def on_post_tool_failure(tool_data: dict):
        return await hook.on_tool_failure(tool_data)

    async def on_stop(event_data: dict):
        return await hook.on_turn_complete(event_data)

    return {
        "hook": hook,
        "on_prompt_generated": on_prompt_generated,
        "on_post_tool_use": on_post_tool_use,
        "on_post_tool_failure": on_post_tool_failure,
        "on_stop": on_stop
    }


def register_hook(daemon=None) -> bool:
    """Register meta-prompter evolution hook with Evolution Daemon."""
    try:
        if daemon is None:
            from systems.evolution_daemon.evolution_daemon import EvolutionDaemon
            daemon = EvolutionDaemon()

        hook = MetaPrompterEvolutionHook()

        if hasattr(daemon, 'register_hook'):
            daemon.register_hook('PostToolUse', hook.on_tool_success)
            daemon.register_hook('PostToolUseFailure', hook.on_tool_failure)
            daemon.register_hook('evolution_cycle', hook.on_evolution_cycle)
            logger.info("Meta-prompter evolution hook registered")
            return True
        else:
            logger.warning("Daemon doesn't support hooks")
            return False

    except Exception as e:
        logger.warning(f"Meta-prompter evolution hook registration failed: {e}")
        return False
